#ifndef PipesValveDiscrete__H
#define PipesValveDiscrete__H
#include "meta/meta_modelica.h"
#include "util/modelica.h"
#include <stdio.h>
#include <stdlib.h>
#include <errno.h>

#include "simulation/simulation_runtime.h"
#ifdef __cplusplus
extern "C" {
#endif

typedef struct Modelica_Fluid_Vessels_BaseClasses_VesselFluidPorts__b$tank1$ports_Medium_FluidConstants_s {
  modelica_string _casRegistryNumber;
  modelica_string _chemicalFormula;
  modelica_string _iupacName;
  modelica_real _molarMass;
  modelica_string _structureFormula;
} Modelica_Fluid_Vessels_BaseClasses_VesselFluidPorts__b$tank1$ports_Medium_FluidConstants;
typedef base_array_t Modelica_Fluid_Vessels_BaseClasses_VesselFluidPorts__b$tank1$ports_Medium_FluidConstants_array;
extern struct record_description Modelica_Fluid_Vessels_BaseClasses_VesselFluidPorts__b$tank1$ports_Medium_FluidConstants__desc;

typedef struct Modelica_Fluid_Pipes_StaticPipe$pipe_FlowModel$pipe$flowModel_Medium_ThermodynamicState_s {
  modelica_real _T;
  modelica_real _p;
} Modelica_Fluid_Pipes_StaticPipe$pipe_FlowModel$pipe$flowModel_Medium_ThermodynamicState;
typedef base_array_t Modelica_Fluid_Pipes_StaticPipe$pipe_FlowModel$pipe$flowModel_Medium_ThermodynamicState_array;
extern struct record_description Modelica_Fluid_Pipes_StaticPipe$pipe_FlowModel$pipe$flowModel_Medium_ThermodynamicState__desc;

typedef struct Modelica_Fluid_Vessels_BaseClasses_VesselPortsData_s {
  modelica_real _diameter;
  modelica_real _height;
  modelica_real _zeta_in;
  modelica_real _zeta_out;
} Modelica_Fluid_Vessels_BaseClasses_VesselPortsData;
typedef base_array_t Modelica_Fluid_Vessels_BaseClasses_VesselPortsData_array;
extern struct record_description Modelica_Fluid_Vessels_BaseClasses_VesselPortsData__desc;

typedef Modelica_Fluid_Vessels_BaseClasses_VesselFluidPorts__b$tank1$ports_Medium_FluidConstants Modelica_Fluid_Pipes_StaticPipe$pipe_FlowModel$pipe$flowModel_Medium_FluidConstants;
typedef base_array_t Modelica_Fluid_Pipes_StaticPipe$pipe_FlowModel$pipe$flowModel_Medium_FluidConstants_array;
extern struct record_description Modelica_Fluid_Pipes_StaticPipe$pipe_FlowModel$pipe$flowModel_Medium_FluidConstants__desc;

typedef Modelica_Fluid_Vessels_BaseClasses_VesselFluidPorts__b$tank1$ports_Medium_FluidConstants Modelica_Fluid_Interfaces_FluidPort__b$pipe$port__b_Medium_FluidConstants;
typedef base_array_t Modelica_Fluid_Interfaces_FluidPort__b$pipe$port__b_Medium_FluidConstants_array;
extern struct record_description Modelica_Fluid_Interfaces_FluidPort__b$pipe$port__b_Medium_FluidConstants__desc;

typedef Modelica_Fluid_Vessels_BaseClasses_VesselFluidPorts__b$tank1$ports_Medium_FluidConstants Modelica_Fluid_Interfaces_FluidPort__a$valve$port__a_Medium_FluidConstants;
typedef base_array_t Modelica_Fluid_Interfaces_FluidPort__a$valve$port__a_Medium_FluidConstants_array;
extern struct record_description Modelica_Fluid_Interfaces_FluidPort__a$valve$port__a_Medium_FluidConstants__desc;

typedef Modelica_Fluid_Vessels_BaseClasses_VesselFluidPorts__b$tank1$ports_Medium_FluidConstants Modelica_Fluid_Interfaces_FluidPort__a$pipe$port__a_Medium_FluidConstants;
typedef base_array_t Modelica_Fluid_Interfaces_FluidPort__a$pipe$port__a_Medium_FluidConstants_array;
extern struct record_description Modelica_Fluid_Interfaces_FluidPort__a$pipe$port__a_Medium_FluidConstants__desc;

typedef Modelica_Fluid_Vessels_BaseClasses_VesselFluidPorts__b$tank1$ports_Medium_FluidConstants Modelica_Fluid_Interfaces_FluidPort__b$valve$port__b_Medium_FluidConstants;
typedef base_array_t Modelica_Fluid_Interfaces_FluidPort__b$valve$port__b_Medium_FluidConstants_array;
extern struct record_description Modelica_Fluid_Interfaces_FluidPort__b$valve$port__b_Medium_FluidConstants__desc;

typedef Modelica_Fluid_Vessels_BaseClasses_VesselFluidPorts__b$tank1$ports_Medium_FluidConstants Modelica_Fluid_Pipes_StaticPipe$pipe_Medium_FluidConstants;
typedef base_array_t Modelica_Fluid_Pipes_StaticPipe$pipe_Medium_FluidConstants_array;
extern struct record_description Modelica_Fluid_Pipes_StaticPipe$pipe_Medium_FluidConstants__desc;

typedef Modelica_Fluid_Vessels_BaseClasses_VesselFluidPorts__b$tank1$ports_Medium_FluidConstants Modelica_Fluid_Valves_ValveDiscrete$valve_Medium_FluidConstants;
typedef base_array_t Modelica_Fluid_Valves_ValveDiscrete$valve_Medium_FluidConstants_array;
extern struct record_description Modelica_Fluid_Valves_ValveDiscrete$valve_Medium_FluidConstants__desc;

typedef Modelica_Fluid_Vessels_BaseClasses_VesselFluidPorts__b$tank1$ports_Medium_FluidConstants Modelica_Fluid_Vessels_OpenTank$tank2_HeatTransfer$tank2$heatTransfer_Medium_FluidConstants;
typedef base_array_t Modelica_Fluid_Vessels_OpenTank$tank2_HeatTransfer$tank2$heatTransfer_Medium_FluidConstants_array;
extern struct record_description Modelica_Fluid_Vessels_OpenTank$tank2_HeatTransfer$tank2$heatTransfer_Medium_FluidConstants__desc;

typedef Modelica_Fluid_Vessels_BaseClasses_VesselFluidPorts__b$tank1$ports_Medium_FluidConstants Modelica_Fluid_Vessels_OpenTank$tank1_Medium_FluidConstants;
typedef base_array_t Modelica_Fluid_Vessels_OpenTank$tank1_Medium_FluidConstants_array;
extern struct record_description Modelica_Fluid_Vessels_OpenTank$tank1_Medium_FluidConstants__desc;

typedef Modelica_Fluid_Vessels_BaseClasses_VesselFluidPorts__b$tank1$ports_Medium_FluidConstants Modelica_Fluid_Vessels_OpenTank$tank1_HeatTransfer$tank1$heatTransfer_Medium_FluidConstants;
typedef base_array_t Modelica_Fluid_Vessels_OpenTank$tank1_HeatTransfer$tank1$heatTransfer_Medium_FluidConstants_array;
extern struct record_description Modelica_Fluid_Vessels_OpenTank$tank1_HeatTransfer$tank1$heatTransfer_Medium_FluidConstants__desc;

typedef Modelica_Fluid_Vessels_BaseClasses_VesselFluidPorts__b$tank1$ports_Medium_FluidConstants Modelica_Fluid_Vessels_BaseClasses_VesselFluidPorts__b$tank2$ports_Medium_FluidConstants;
typedef base_array_t Modelica_Fluid_Vessels_BaseClasses_VesselFluidPorts__b$tank2$ports_Medium_FluidConstants_array;
extern struct record_description Modelica_Fluid_Vessels_BaseClasses_VesselFluidPorts__b$tank2$ports_Medium_FluidConstants__desc;

typedef Modelica_Fluid_Vessels_BaseClasses_VesselFluidPorts__b$tank1$ports_Medium_FluidConstants Modelica_Fluid_Vessels_OpenTank$tank2_Medium_FluidConstants;
typedef base_array_t Modelica_Fluid_Vessels_OpenTank$tank2_Medium_FluidConstants_array;
extern struct record_description Modelica_Fluid_Vessels_OpenTank$tank2_Medium_FluidConstants__desc;

typedef Modelica_Fluid_Vessels_BaseClasses_VesselFluidPorts__b$tank1$ports_Medium_FluidConstants Modelica_Media_Interfaces_Types_Basic_FluidConstants$simpleWaterConstants;
typedef base_array_t Modelica_Media_Interfaces_Types_Basic_FluidConstants$simpleWaterConstants_array;
extern struct record_description Modelica_Media_Interfaces_Types_Basic_FluidConstants$simpleWaterConstants__desc;

typedef Modelica_Fluid_Vessels_BaseClasses_VesselFluidPorts__b$tank1$ports_Medium_FluidConstants Modelica_Media_Interfaces_Types_Basic_FluidConstants;
typedef base_array_t Modelica_Media_Interfaces_Types_Basic_FluidConstants_array;
extern struct record_description Modelica_Media_Interfaces_Types_Basic_FluidConstants__desc;

typedef Modelica_Fluid_Pipes_StaticPipe$pipe_FlowModel$pipe$flowModel_Medium_ThermodynamicState Modelica_Fluid_Pipes_StaticPipe$pipe_Medium_ThermodynamicState;
typedef base_array_t Modelica_Fluid_Pipes_StaticPipe$pipe_Medium_ThermodynamicState_array;
extern struct record_description Modelica_Fluid_Pipes_StaticPipe$pipe_Medium_ThermodynamicState__desc;

typedef Modelica_Fluid_Pipes_StaticPipe$pipe_FlowModel$pipe$flowModel_Medium_ThermodynamicState Modelica_Fluid_Valves_ValveDiscrete$valve_Medium_ThermodynamicState;
typedef base_array_t Modelica_Fluid_Valves_ValveDiscrete$valve_Medium_ThermodynamicState_array;
extern struct record_description Modelica_Fluid_Valves_ValveDiscrete$valve_Medium_ThermodynamicState__desc;

typedef Modelica_Fluid_Pipes_StaticPipe$pipe_FlowModel$pipe$flowModel_Medium_ThermodynamicState Modelica_Fluid_Vessels_OpenTank$tank1_HeatTransfer$tank1$heatTransfer_Medium_ThermodynamicState;
typedef base_array_t Modelica_Fluid_Vessels_OpenTank$tank1_HeatTransfer$tank1$heatTransfer_Medium_ThermodynamicState_array;
extern struct record_description Modelica_Fluid_Vessels_OpenTank$tank1_HeatTransfer$tank1$heatTransfer_Medium_ThermodynamicState__desc;

typedef Modelica_Fluid_Pipes_StaticPipe$pipe_FlowModel$pipe$flowModel_Medium_ThermodynamicState Modelica_Fluid_Vessels_OpenTank$tank1_Medium_ThermodynamicState;
typedef base_array_t Modelica_Fluid_Vessels_OpenTank$tank1_Medium_ThermodynamicState_array;
extern struct record_description Modelica_Fluid_Vessels_OpenTank$tank1_Medium_ThermodynamicState__desc;

typedef Modelica_Fluid_Pipes_StaticPipe$pipe_FlowModel$pipe$flowModel_Medium_ThermodynamicState Modelica_Fluid_Vessels_OpenTank$tank2_Medium_ThermodynamicState;
typedef base_array_t Modelica_Fluid_Vessels_OpenTank$tank2_Medium_ThermodynamicState_array;
extern struct record_description Modelica_Fluid_Vessels_OpenTank$tank2_Medium_ThermodynamicState__desc;

typedef Modelica_Fluid_Pipes_StaticPipe$pipe_FlowModel$pipe$flowModel_Medium_ThermodynamicState Modelica_Fluid_Vessels_OpenTank$tank2_HeatTransfer$tank2$heatTransfer_Medium_ThermodynamicState;
typedef base_array_t Modelica_Fluid_Vessels_OpenTank$tank2_HeatTransfer$tank2$heatTransfer_Medium_ThermodynamicState_array;
extern struct record_description Modelica_Fluid_Vessels_OpenTank$tank2_HeatTransfer$tank2$heatTransfer_Medium_ThermodynamicState__desc;

DLLExport
Modelica_Fluid_Vessels_BaseClasses_VesselFluidPorts__b$tank1$ports_Medium_FluidConstants omc_Modelica_Fluid_Vessels_BaseClasses_VesselFluidPorts__b$tank1$ports_Medium_FluidConstants(threadData_t *threadData, modelica_string iupacName, modelica_string casRegistryNumber, modelica_string chemicalFormula, modelica_string structureFormula, modelica_real molarMass); /* record head */

DLLExport
modelica_metatype boxptr_Modelica_Fluid_Vessels_BaseClasses_VesselFluidPorts__b$tank1$ports_Medium_FluidConstants(threadData_t *threadData, modelica_metatype _iupacName, modelica_metatype _casRegistryNumber, modelica_metatype _chemicalFormula, modelica_metatype _structureFormula, modelica_metatype _molarMass);
static const MMC_DEFSTRUCTLIT(boxvar_lit_Modelica_Fluid_Vessels_BaseClasses_VesselFluidPorts__b$tank1$ports_Medium_FluidConstants,2,0) {(void*) boxptr_Modelica_Fluid_Vessels_BaseClasses_VesselFluidPorts__b$tank1$ports_Medium_FluidConstants,0}};
#define boxvar_Modelica_Fluid_Vessels_BaseClasses_VesselFluidPorts__b$tank1$ports_Medium_FluidConstants MMC_REFSTRUCTLIT(boxvar_lit_Modelica_Fluid_Vessels_BaseClasses_VesselFluidPorts__b$tank1$ports_Medium_FluidConstants)


DLLExport
modelica_real omc_Modelica_Fluid_Utilities_regSquare2(threadData_t *threadData, modelica_real _x, modelica_real _x_small, modelica_real _k1, modelica_real _k2, modelica_boolean _use_yd0, modelica_real _yd0);
DLLExport
modelica_metatype boxptr_Modelica_Fluid_Utilities_regSquare2(threadData_t *threadData, modelica_metatype _x, modelica_metatype _x_small, modelica_metatype _k1, modelica_metatype _k2, modelica_metatype _use_yd0, modelica_metatype _yd0);
static const MMC_DEFSTRUCTLIT(boxvar_lit_Modelica_Fluid_Utilities_regSquare2,2,0) {(void*) boxptr_Modelica_Fluid_Utilities_regSquare2,0}};
#define boxvar_Modelica_Fluid_Utilities_regSquare2 MMC_REFSTRUCTLIT(boxvar_lit_Modelica_Fluid_Utilities_regSquare2)


DLLExport
modelica_real omc_Modelica_Fluid_Pipes_StaticPipe$pipe_FlowModel$pipe$flowModel_WallFriction_massFlowRate__dp__staticHead(threadData_t *threadData, modelica_real _dp, modelica_real _rho_a, modelica_real _rho_b, modelica_real _mu_a, modelica_real _mu_b, modelica_real _length, modelica_real _diameter, modelica_real _g_times_height_ab, modelica_real _crossArea, modelica_real _roughness, modelica_real _dp_small, modelica_real _Re_turbulent);
DLLExport
modelica_metatype boxptr_Modelica_Fluid_Pipes_StaticPipe$pipe_FlowModel$pipe$flowModel_WallFriction_massFlowRate__dp__staticHead(threadData_t *threadData, modelica_metatype _dp, modelica_metatype _rho_a, modelica_metatype _rho_b, modelica_metatype _mu_a, modelica_metatype _mu_b, modelica_metatype _length, modelica_metatype _diameter, modelica_metatype _g_times_height_ab, modelica_metatype _crossArea, modelica_metatype _roughness, modelica_metatype _dp_small, modelica_metatype _Re_turbulent);
static const MMC_DEFSTRUCTLIT(boxvar_lit_Modelica_Fluid_Pipes_StaticPipe$pipe_FlowModel$pipe$flowModel_WallFriction_massFlowRate__dp__staticHead,2,0) {(void*) boxptr_Modelica_Fluid_Pipes_StaticPipe$pipe_FlowModel$pipe$flowModel_WallFriction_massFlowRate__dp__staticHead,0}};
#define boxvar_Modelica_Fluid_Pipes_StaticPipe$pipe_FlowModel$pipe$flowModel_WallFriction_massFlowRate__dp__staticHead MMC_REFSTRUCTLIT(boxvar_lit_Modelica_Fluid_Pipes_StaticPipe$pipe_FlowModel$pipe$flowModel_WallFriction_massFlowRate__dp__staticHead)


DLLExport
Modelica_Fluid_Pipes_StaticPipe$pipe_FlowModel$pipe$flowModel_Medium_FluidConstants omc_Modelica_Fluid_Pipes_StaticPipe$pipe_FlowModel$pipe$flowModel_Medium_FluidConstants(threadData_t *threadData, modelica_string iupacName, modelica_string casRegistryNumber, modelica_string chemicalFormula, modelica_string structureFormula, modelica_real molarMass); /* record head */

DLLExport
modelica_metatype boxptr_Modelica_Fluid_Pipes_StaticPipe$pipe_FlowModel$pipe$flowModel_Medium_FluidConstants(threadData_t *threadData, modelica_metatype _iupacName, modelica_metatype _casRegistryNumber, modelica_metatype _chemicalFormula, modelica_metatype _structureFormula, modelica_metatype _molarMass);
static const MMC_DEFSTRUCTLIT(boxvar_lit_Modelica_Fluid_Pipes_StaticPipe$pipe_FlowModel$pipe$flowModel_Medium_FluidConstants,2,0) {(void*) boxptr_Modelica_Fluid_Pipes_StaticPipe$pipe_FlowModel$pipe$flowModel_Medium_FluidConstants,0}};
#define boxvar_Modelica_Fluid_Pipes_StaticPipe$pipe_FlowModel$pipe$flowModel_Medium_FluidConstants MMC_REFSTRUCTLIT(boxvar_lit_Modelica_Fluid_Pipes_StaticPipe$pipe_FlowModel$pipe$flowModel_Medium_FluidConstants)


DLLExport
Modelica_Fluid_Interfaces_FluidPort__b$pipe$port__b_Medium_FluidConstants omc_Modelica_Fluid_Interfaces_FluidPort__b$pipe$port__b_Medium_FluidConstants(threadData_t *threadData, modelica_string iupacName, modelica_string casRegistryNumber, modelica_string chemicalFormula, modelica_string structureFormula, modelica_real molarMass); /* record head */

DLLExport
modelica_metatype boxptr_Modelica_Fluid_Interfaces_FluidPort__b$pipe$port__b_Medium_FluidConstants(threadData_t *threadData, modelica_metatype _iupacName, modelica_metatype _casRegistryNumber, modelica_metatype _chemicalFormula, modelica_metatype _structureFormula, modelica_metatype _molarMass);
static const MMC_DEFSTRUCTLIT(boxvar_lit_Modelica_Fluid_Interfaces_FluidPort__b$pipe$port__b_Medium_FluidConstants,2,0) {(void*) boxptr_Modelica_Fluid_Interfaces_FluidPort__b$pipe$port__b_Medium_FluidConstants,0}};
#define boxvar_Modelica_Fluid_Interfaces_FluidPort__b$pipe$port__b_Medium_FluidConstants MMC_REFSTRUCTLIT(boxvar_lit_Modelica_Fluid_Interfaces_FluidPort__b$pipe$port__b_Medium_FluidConstants)


DLLExport
Modelica_Fluid_Interfaces_FluidPort__a$valve$port__a_Medium_FluidConstants omc_Modelica_Fluid_Interfaces_FluidPort__a$valve$port__a_Medium_FluidConstants(threadData_t *threadData, modelica_string iupacName, modelica_string casRegistryNumber, modelica_string chemicalFormula, modelica_string structureFormula, modelica_real molarMass); /* record head */

DLLExport
modelica_metatype boxptr_Modelica_Fluid_Interfaces_FluidPort__a$valve$port__a_Medium_FluidConstants(threadData_t *threadData, modelica_metatype _iupacName, modelica_metatype _casRegistryNumber, modelica_metatype _chemicalFormula, modelica_metatype _structureFormula, modelica_metatype _molarMass);
static const MMC_DEFSTRUCTLIT(boxvar_lit_Modelica_Fluid_Interfaces_FluidPort__a$valve$port__a_Medium_FluidConstants,2,0) {(void*) boxptr_Modelica_Fluid_Interfaces_FluidPort__a$valve$port__a_Medium_FluidConstants,0}};
#define boxvar_Modelica_Fluid_Interfaces_FluidPort__a$valve$port__a_Medium_FluidConstants MMC_REFSTRUCTLIT(boxvar_lit_Modelica_Fluid_Interfaces_FluidPort__a$valve$port__a_Medium_FluidConstants)


DLLExport
Modelica_Fluid_Interfaces_FluidPort__a$pipe$port__a_Medium_FluidConstants omc_Modelica_Fluid_Interfaces_FluidPort__a$pipe$port__a_Medium_FluidConstants(threadData_t *threadData, modelica_string iupacName, modelica_string casRegistryNumber, modelica_string chemicalFormula, modelica_string structureFormula, modelica_real molarMass); /* record head */

DLLExport
modelica_metatype boxptr_Modelica_Fluid_Interfaces_FluidPort__a$pipe$port__a_Medium_FluidConstants(threadData_t *threadData, modelica_metatype _iupacName, modelica_metatype _casRegistryNumber, modelica_metatype _chemicalFormula, modelica_metatype _structureFormula, modelica_metatype _molarMass);
static const MMC_DEFSTRUCTLIT(boxvar_lit_Modelica_Fluid_Interfaces_FluidPort__a$pipe$port__a_Medium_FluidConstants,2,0) {(void*) boxptr_Modelica_Fluid_Interfaces_FluidPort__a$pipe$port__a_Medium_FluidConstants,0}};
#define boxvar_Modelica_Fluid_Interfaces_FluidPort__a$pipe$port__a_Medium_FluidConstants MMC_REFSTRUCTLIT(boxvar_lit_Modelica_Fluid_Interfaces_FluidPort__a$pipe$port__a_Medium_FluidConstants)


DLLExport
Modelica_Fluid_Interfaces_FluidPort__b$valve$port__b_Medium_FluidConstants omc_Modelica_Fluid_Interfaces_FluidPort__b$valve$port__b_Medium_FluidConstants(threadData_t *threadData, modelica_string iupacName, modelica_string casRegistryNumber, modelica_string chemicalFormula, modelica_string structureFormula, modelica_real molarMass); /* record head */

DLLExport
modelica_metatype boxptr_Modelica_Fluid_Interfaces_FluidPort__b$valve$port__b_Medium_FluidConstants(threadData_t *threadData, modelica_metatype _iupacName, modelica_metatype _casRegistryNumber, modelica_metatype _chemicalFormula, modelica_metatype _structureFormula, modelica_metatype _molarMass);
static const MMC_DEFSTRUCTLIT(boxvar_lit_Modelica_Fluid_Interfaces_FluidPort__b$valve$port__b_Medium_FluidConstants,2,0) {(void*) boxptr_Modelica_Fluid_Interfaces_FluidPort__b$valve$port__b_Medium_FluidConstants,0}};
#define boxvar_Modelica_Fluid_Interfaces_FluidPort__b$valve$port__b_Medium_FluidConstants MMC_REFSTRUCTLIT(boxvar_lit_Modelica_Fluid_Interfaces_FluidPort__b$valve$port__b_Medium_FluidConstants)


DLLExport
modelica_real omc_Modelica_Fluid_Pipes_StaticPipe$pipe_FlowModel$pipe$flowModel_Medium_density(threadData_t *threadData, Modelica_Fluid_Pipes_StaticPipe$pipe_FlowModel$pipe$flowModel_Medium_ThermodynamicState _state);
DLLExport
modelica_metatype boxptr_Modelica_Fluid_Pipes_StaticPipe$pipe_FlowModel$pipe$flowModel_Medium_density(threadData_t *threadData, modelica_metatype _state);
static const MMC_DEFSTRUCTLIT(boxvar_lit_Modelica_Fluid_Pipes_StaticPipe$pipe_FlowModel$pipe$flowModel_Medium_density,2,0) {(void*) boxptr_Modelica_Fluid_Pipes_StaticPipe$pipe_FlowModel$pipe$flowModel_Medium_density,0}};
#define boxvar_Modelica_Fluid_Pipes_StaticPipe$pipe_FlowModel$pipe$flowModel_Medium_density MMC_REFSTRUCTLIT(boxvar_lit_Modelica_Fluid_Pipes_StaticPipe$pipe_FlowModel$pipe$flowModel_Medium_density)


DLLExport
Modelica_Fluid_Pipes_StaticPipe$pipe_FlowModel$pipe$flowModel_Medium_ThermodynamicState omc_Modelica_Fluid_Pipes_StaticPipe$pipe_FlowModel$pipe$flowModel_Medium_ThermodynamicState(threadData_t *threadData, modelica_real p, modelica_real T); /* record head */

DLLExport
modelica_metatype boxptr_Modelica_Fluid_Pipes_StaticPipe$pipe_FlowModel$pipe$flowModel_Medium_ThermodynamicState(threadData_t *threadData, modelica_metatype _p, modelica_metatype _T);
static const MMC_DEFSTRUCTLIT(boxvar_lit_Modelica_Fluid_Pipes_StaticPipe$pipe_FlowModel$pipe$flowModel_Medium_ThermodynamicState,2,0) {(void*) boxptr_Modelica_Fluid_Pipes_StaticPipe$pipe_FlowModel$pipe$flowModel_Medium_ThermodynamicState,0}};
#define boxvar_Modelica_Fluid_Pipes_StaticPipe$pipe_FlowModel$pipe$flowModel_Medium_ThermodynamicState MMC_REFSTRUCTLIT(boxvar_lit_Modelica_Fluid_Pipes_StaticPipe$pipe_FlowModel$pipe$flowModel_Medium_ThermodynamicState)


DLLExport
modelica_real omc_Modelica_Fluid_Pipes_StaticPipe$pipe_FlowModel$pipe$flowModel_Medium_pressure(threadData_t *threadData, Modelica_Fluid_Pipes_StaticPipe$pipe_FlowModel$pipe$flowModel_Medium_ThermodynamicState _state);
DLLExport
modelica_metatype boxptr_Modelica_Fluid_Pipes_StaticPipe$pipe_FlowModel$pipe$flowModel_Medium_pressure(threadData_t *threadData, modelica_metatype _state);
static const MMC_DEFSTRUCTLIT(boxvar_lit_Modelica_Fluid_Pipes_StaticPipe$pipe_FlowModel$pipe$flowModel_Medium_pressure,2,0) {(void*) boxptr_Modelica_Fluid_Pipes_StaticPipe$pipe_FlowModel$pipe$flowModel_Medium_pressure,0}};
#define boxvar_Modelica_Fluid_Pipes_StaticPipe$pipe_FlowModel$pipe$flowModel_Medium_pressure MMC_REFSTRUCTLIT(boxvar_lit_Modelica_Fluid_Pipes_StaticPipe$pipe_FlowModel$pipe$flowModel_Medium_pressure)


DLLExport
modelica_real omc_Modelica_Fluid_Pipes_StaticPipe$pipe_FlowModel$pipe$flowModel_Medium_dynamicViscosity(threadData_t *threadData, Modelica_Fluid_Pipes_StaticPipe$pipe_FlowModel$pipe$flowModel_Medium_ThermodynamicState _state);
DLLExport
modelica_metatype boxptr_Modelica_Fluid_Pipes_StaticPipe$pipe_FlowModel$pipe$flowModel_Medium_dynamicViscosity(threadData_t *threadData, modelica_metatype _state);
static const MMC_DEFSTRUCTLIT(boxvar_lit_Modelica_Fluid_Pipes_StaticPipe$pipe_FlowModel$pipe$flowModel_Medium_dynamicViscosity,2,0) {(void*) boxptr_Modelica_Fluid_Pipes_StaticPipe$pipe_FlowModel$pipe$flowModel_Medium_dynamicViscosity,0}};
#define boxvar_Modelica_Fluid_Pipes_StaticPipe$pipe_FlowModel$pipe$flowModel_Medium_dynamicViscosity MMC_REFSTRUCTLIT(boxvar_lit_Modelica_Fluid_Pipes_StaticPipe$pipe_FlowModel$pipe$flowModel_Medium_dynamicViscosity)


DLLExport
Modelica_Fluid_Pipes_StaticPipe$pipe_Medium_FluidConstants omc_Modelica_Fluid_Pipes_StaticPipe$pipe_Medium_FluidConstants(threadData_t *threadData, modelica_string iupacName, modelica_string casRegistryNumber, modelica_string chemicalFormula, modelica_string structureFormula, modelica_real molarMass); /* record head */

DLLExport
modelica_metatype boxptr_Modelica_Fluid_Pipes_StaticPipe$pipe_Medium_FluidConstants(threadData_t *threadData, modelica_metatype _iupacName, modelica_metatype _casRegistryNumber, modelica_metatype _chemicalFormula, modelica_metatype _structureFormula, modelica_metatype _molarMass);
static const MMC_DEFSTRUCTLIT(boxvar_lit_Modelica_Fluid_Pipes_StaticPipe$pipe_Medium_FluidConstants,2,0) {(void*) boxptr_Modelica_Fluid_Pipes_StaticPipe$pipe_Medium_FluidConstants,0}};
#define boxvar_Modelica_Fluid_Pipes_StaticPipe$pipe_Medium_FluidConstants MMC_REFSTRUCTLIT(boxvar_lit_Modelica_Fluid_Pipes_StaticPipe$pipe_Medium_FluidConstants)


DLLExport
modelica_real omc_Modelica_Fluid_Pipes_StaticPipe$pipe_FlowModel$pipe$flowModel_WallFriction_Internal_m__flow__of__dp__fric(threadData_t *threadData, modelica_real _dp_fric, modelica_real _rho_a, modelica_real _rho_b, modelica_real _mu_a, modelica_real _mu_b, modelica_real _length, modelica_real _diameter, modelica_real _crossArea, modelica_real _Re1, modelica_real _Re2, modelica_real _Delta, modelica_real *out_dm_flow_ddp_fric);
DLLExport
modelica_metatype boxptr_Modelica_Fluid_Pipes_StaticPipe$pipe_FlowModel$pipe$flowModel_WallFriction_Internal_m__flow__of__dp__fric(threadData_t *threadData, modelica_metatype _dp_fric, modelica_metatype _rho_a, modelica_metatype _rho_b, modelica_metatype _mu_a, modelica_metatype _mu_b, modelica_metatype _length, modelica_metatype _diameter, modelica_metatype _crossArea, modelica_metatype _Re1, modelica_metatype _Re2, modelica_metatype _Delta, modelica_metatype *out_dm_flow_ddp_fric);
static const MMC_DEFSTRUCTLIT(boxvar_lit_Modelica_Fluid_Pipes_StaticPipe$pipe_FlowModel$pipe$flowModel_WallFriction_Internal_m__flow__of__dp__fric,2,0) {(void*) boxptr_Modelica_Fluid_Pipes_StaticPipe$pipe_FlowModel$pipe$flowModel_WallFriction_Internal_m__flow__of__dp__fric,0}};
#define boxvar_Modelica_Fluid_Pipes_StaticPipe$pipe_FlowModel$pipe$flowModel_WallFriction_Internal_m__flow__of__dp__fric MMC_REFSTRUCTLIT(boxvar_lit_Modelica_Fluid_Pipes_StaticPipe$pipe_FlowModel$pipe$flowModel_WallFriction_Internal_m__flow__of__dp__fric)


DLLExport
modelica_real omc_Modelica_Fluid_Pipes_StaticPipe$pipe_FlowModel$pipe$flowModel_WallFriction_pressureLoss__m__flow(threadData_t *threadData, modelica_real _m_flow, modelica_real _rho_a, modelica_real _rho_b, modelica_real _mu_a, modelica_real _mu_b, modelica_real _length, modelica_real _diameter, modelica_real _crossArea, modelica_real _roughness, modelica_real _m_flow_small, modelica_real _Re_turbulent);
DLLExport
modelica_metatype boxptr_Modelica_Fluid_Pipes_StaticPipe$pipe_FlowModel$pipe$flowModel_WallFriction_pressureLoss__m__flow(threadData_t *threadData, modelica_metatype _m_flow, modelica_metatype _rho_a, modelica_metatype _rho_b, modelica_metatype _mu_a, modelica_metatype _mu_b, modelica_metatype _length, modelica_metatype _diameter, modelica_metatype _crossArea, modelica_metatype _roughness, modelica_metatype _m_flow_small, modelica_metatype _Re_turbulent);
static const MMC_DEFSTRUCTLIT(boxvar_lit_Modelica_Fluid_Pipes_StaticPipe$pipe_FlowModel$pipe$flowModel_WallFriction_pressureLoss__m__flow,2,0) {(void*) boxptr_Modelica_Fluid_Pipes_StaticPipe$pipe_FlowModel$pipe$flowModel_WallFriction_pressureLoss__m__flow,0}};
#define boxvar_Modelica_Fluid_Pipes_StaticPipe$pipe_FlowModel$pipe$flowModel_WallFriction_pressureLoss__m__flow MMC_REFSTRUCTLIT(boxvar_lit_Modelica_Fluid_Pipes_StaticPipe$pipe_FlowModel$pipe$flowModel_WallFriction_pressureLoss__m__flow)


modelica_real omc_Modelica_Fluid_Pipes_StaticPipe$pipe_FlowModel$pipe$flowModel_WallFriction_Internal_m__flow__of__dp__fric_interpolateInRegion2__withDerivative(threadData_t *threadData, modelica_real _lambda2, modelica_real _Re1, modelica_real _Re2, modelica_real _Delta, modelica_real _dp_fric, modelica_real *out_dRe_ddp);
modelica_metatype boxptr_Modelica_Fluid_Pipes_StaticPipe$pipe_FlowModel$pipe$flowModel_WallFriction_Internal_m__flow__of__dp__fric_interpolateInRegion2__withDerivative(threadData_t *threadData, modelica_metatype _lambda2, modelica_metatype _Re1, modelica_metatype _Re2, modelica_metatype _Delta, modelica_metatype _dp_fric, modelica_metatype *out_dRe_ddp);
static const MMC_DEFSTRUCTLIT(boxvar_lit_Modelica_Fluid_Pipes_StaticPipe$pipe_FlowModel$pipe$flowModel_WallFriction_Internal_m__flow__of__dp__fric_interpolateInRegion2__withDerivative,2,0) {(void*) boxptr_Modelica_Fluid_Pipes_StaticPipe$pipe_FlowModel$pipe$flowModel_WallFriction_Internal_m__flow__of__dp__fric_interpolateInRegion2__withDerivative,0}};
#define boxvar_Modelica_Fluid_Pipes_StaticPipe$pipe_FlowModel$pipe$flowModel_WallFriction_Internal_m__flow__of__dp__fric_interpolateInRegion2__withDerivative MMC_REFSTRUCTLIT(boxvar_lit_Modelica_Fluid_Pipes_StaticPipe$pipe_FlowModel$pipe$flowModel_WallFriction_Internal_m__flow__of__dp__fric_interpolateInRegion2__withDerivative)
 /* boxvar early */

modelica_real omc_Modelica_Fluid_Pipes_StaticPipe$pipe_FlowModel$pipe$flowModel_WallFriction_pressureLoss__m__flow_interpolateInRegion2(threadData_t *threadData, modelica_real _Re, modelica_real _Re1, modelica_real _Re2, modelica_real _Delta);
modelica_metatype boxptr_Modelica_Fluid_Pipes_StaticPipe$pipe_FlowModel$pipe$flowModel_WallFriction_pressureLoss__m__flow_interpolateInRegion2(threadData_t *threadData, modelica_metatype _Re, modelica_metatype _Re1, modelica_metatype _Re2, modelica_metatype _Delta);
static const MMC_DEFSTRUCTLIT(boxvar_lit_Modelica_Fluid_Pipes_StaticPipe$pipe_FlowModel$pipe$flowModel_WallFriction_pressureLoss__m__flow_interpolateInRegion2,2,0) {(void*) boxptr_Modelica_Fluid_Pipes_StaticPipe$pipe_FlowModel$pipe$flowModel_WallFriction_pressureLoss__m__flow_interpolateInRegion2,0}};
#define boxvar_Modelica_Fluid_Pipes_StaticPipe$pipe_FlowModel$pipe$flowModel_WallFriction_pressureLoss__m__flow_interpolateInRegion2 MMC_REFSTRUCTLIT(boxvar_lit_Modelica_Fluid_Pipes_StaticPipe$pipe_FlowModel$pipe$flowModel_WallFriction_pressureLoss__m__flow_interpolateInRegion2)
 /* boxvar early */

DLLExport
modelica_real omc_Modelica_Fluid_Utilities_cubicHermite__withDerivative(threadData_t *threadData, modelica_real _x, modelica_real _x1, modelica_real _x2, modelica_real _y1, modelica_real _y2, modelica_real _y1d, modelica_real _y2d, modelica_real *out_dy_dx);
DLLExport
modelica_metatype boxptr_Modelica_Fluid_Utilities_cubicHermite__withDerivative(threadData_t *threadData, modelica_metatype _x, modelica_metatype _x1, modelica_metatype _x2, modelica_metatype _y1, modelica_metatype _y2, modelica_metatype _y1d, modelica_metatype _y2d, modelica_metatype *out_dy_dx);
static const MMC_DEFSTRUCTLIT(boxvar_lit_Modelica_Fluid_Utilities_cubicHermite__withDerivative,2,0) {(void*) boxptr_Modelica_Fluid_Utilities_cubicHermite__withDerivative,0}};
#define boxvar_Modelica_Fluid_Utilities_cubicHermite__withDerivative MMC_REFSTRUCTLIT(boxvar_lit_Modelica_Fluid_Utilities_cubicHermite__withDerivative)


DLLExport
Modelica_Fluid_Pipes_StaticPipe$pipe_Medium_ThermodynamicState omc_Modelica_Fluid_Pipes_StaticPipe$pipe_Medium_ThermodynamicState(threadData_t *threadData, modelica_real p, modelica_real T); /* record head */

DLLExport
modelica_metatype boxptr_Modelica_Fluid_Pipes_StaticPipe$pipe_Medium_ThermodynamicState(threadData_t *threadData, modelica_metatype _p, modelica_metatype _T);
static const MMC_DEFSTRUCTLIT(boxvar_lit_Modelica_Fluid_Pipes_StaticPipe$pipe_Medium_ThermodynamicState,2,0) {(void*) boxptr_Modelica_Fluid_Pipes_StaticPipe$pipe_Medium_ThermodynamicState,0}};
#define boxvar_Modelica_Fluid_Pipes_StaticPipe$pipe_Medium_ThermodynamicState MMC_REFSTRUCTLIT(boxvar_lit_Modelica_Fluid_Pipes_StaticPipe$pipe_Medium_ThermodynamicState)


DLLExport
modelica_real omc_Modelica_Fluid_Pipes_StaticPipe$pipe_Medium_density(threadData_t *threadData, Modelica_Fluid_Pipes_StaticPipe$pipe_Medium_ThermodynamicState _state);
DLLExport
modelica_metatype boxptr_Modelica_Fluid_Pipes_StaticPipe$pipe_Medium_density(threadData_t *threadData, modelica_metatype _state);
static const MMC_DEFSTRUCTLIT(boxvar_lit_Modelica_Fluid_Pipes_StaticPipe$pipe_Medium_density,2,0) {(void*) boxptr_Modelica_Fluid_Pipes_StaticPipe$pipe_Medium_density,0}};
#define boxvar_Modelica_Fluid_Pipes_StaticPipe$pipe_Medium_density MMC_REFSTRUCTLIT(boxvar_lit_Modelica_Fluid_Pipes_StaticPipe$pipe_Medium_density)


DLLExport
modelica_real omc_Modelica_Fluid_Utilities_evaluatePoly3__derivativeAtZero(threadData_t *threadData, modelica_real _x, modelica_real _x1, modelica_real _y1, modelica_real _y1d, modelica_real _y0d);
DLLExport
modelica_metatype boxptr_Modelica_Fluid_Utilities_evaluatePoly3__derivativeAtZero(threadData_t *threadData, modelica_metatype _x, modelica_metatype _x1, modelica_metatype _y1, modelica_metatype _y1d, modelica_metatype _y0d);
static const MMC_DEFSTRUCTLIT(boxvar_lit_Modelica_Fluid_Utilities_evaluatePoly3__derivativeAtZero,2,0) {(void*) boxptr_Modelica_Fluid_Utilities_evaluatePoly3__derivativeAtZero,0}};
#define boxvar_Modelica_Fluid_Utilities_evaluatePoly3__derivativeAtZero MMC_REFSTRUCTLIT(boxvar_lit_Modelica_Fluid_Utilities_evaluatePoly3__derivativeAtZero)


DLLExport
modelica_real omc_Modelica_Fluid_Utilities_regFun3(threadData_t *threadData, modelica_real _x, modelica_real _x0, modelica_real _x1, modelica_real _y0, modelica_real _y1, modelica_real _y0d, modelica_real _y1d, modelica_real *out_c);
DLLExport
modelica_metatype boxptr_Modelica_Fluid_Utilities_regFun3(threadData_t *threadData, modelica_metatype _x, modelica_metatype _x0, modelica_metatype _x1, modelica_metatype _y0, modelica_metatype _y1, modelica_metatype _y0d, modelica_metatype _y1d, modelica_metatype *out_c);
static const MMC_DEFSTRUCTLIT(boxvar_lit_Modelica_Fluid_Utilities_regFun3,2,0) {(void*) boxptr_Modelica_Fluid_Utilities_regFun3,0}};
#define boxvar_Modelica_Fluid_Utilities_regFun3 MMC_REFSTRUCTLIT(boxvar_lit_Modelica_Fluid_Utilities_regFun3)


DLLExport
Modelica_Fluid_Valves_ValveDiscrete$valve_Medium_FluidConstants omc_Modelica_Fluid_Valves_ValveDiscrete$valve_Medium_FluidConstants(threadData_t *threadData, modelica_string iupacName, modelica_string casRegistryNumber, modelica_string chemicalFormula, modelica_string structureFormula, modelica_real molarMass); /* record head */

DLLExport
modelica_metatype boxptr_Modelica_Fluid_Valves_ValveDiscrete$valve_Medium_FluidConstants(threadData_t *threadData, modelica_metatype _iupacName, modelica_metatype _casRegistryNumber, modelica_metatype _chemicalFormula, modelica_metatype _structureFormula, modelica_metatype _molarMass);
static const MMC_DEFSTRUCTLIT(boxvar_lit_Modelica_Fluid_Valves_ValveDiscrete$valve_Medium_FluidConstants,2,0) {(void*) boxptr_Modelica_Fluid_Valves_ValveDiscrete$valve_Medium_FluidConstants,0}};
#define boxvar_Modelica_Fluid_Valves_ValveDiscrete$valve_Medium_FluidConstants MMC_REFSTRUCTLIT(boxvar_lit_Modelica_Fluid_Valves_ValveDiscrete$valve_Medium_FluidConstants)


DLLExport
modelica_real omc_Modelica_Fluid_Utilities_regStep(threadData_t *threadData, modelica_real _x, modelica_real _y1, modelica_real _y2, modelica_real _x_small);
DLLExport
modelica_metatype boxptr_Modelica_Fluid_Utilities_regStep(threadData_t *threadData, modelica_metatype _x, modelica_metatype _y1, modelica_metatype _y2, modelica_metatype _x_small);
static const MMC_DEFSTRUCTLIT(boxvar_lit_Modelica_Fluid_Utilities_regStep,2,0) {(void*) boxptr_Modelica_Fluid_Utilities_regStep,0}};
#define boxvar_Modelica_Fluid_Utilities_regStep MMC_REFSTRUCTLIT(boxvar_lit_Modelica_Fluid_Utilities_regStep)


modelica_real omc_Modelica_Fluid_Utilities_regSquare2_regSquare2__utility(threadData_t *threadData, modelica_real _x, modelica_real _x1, modelica_real _k1, modelica_real _k2, modelica_boolean _use_yd0, modelica_real _yd0);
modelica_metatype boxptr_Modelica_Fluid_Utilities_regSquare2_regSquare2__utility(threadData_t *threadData, modelica_metatype _x, modelica_metatype _x1, modelica_metatype _k1, modelica_metatype _k2, modelica_metatype _use_yd0, modelica_metatype _yd0);
static const MMC_DEFSTRUCTLIT(boxvar_lit_Modelica_Fluid_Utilities_regSquare2_regSquare2__utility,2,0) {(void*) boxptr_Modelica_Fluid_Utilities_regSquare2_regSquare2__utility,0}};
#define boxvar_Modelica_Fluid_Utilities_regSquare2_regSquare2__utility MMC_REFSTRUCTLIT(boxvar_lit_Modelica_Fluid_Utilities_regSquare2_regSquare2__utility)
 /* boxvar early */

DLLExport
modelica_real omc_Modelica_Fluid_Valves_ValveDiscrete$valve_Medium_density(threadData_t *threadData, Modelica_Fluid_Valves_ValveDiscrete$valve_Medium_ThermodynamicState _state);
DLLExport
modelica_metatype boxptr_Modelica_Fluid_Valves_ValveDiscrete$valve_Medium_density(threadData_t *threadData, modelica_metatype _state);
static const MMC_DEFSTRUCTLIT(boxvar_lit_Modelica_Fluid_Valves_ValveDiscrete$valve_Medium_density,2,0) {(void*) boxptr_Modelica_Fluid_Valves_ValveDiscrete$valve_Medium_density,0}};
#define boxvar_Modelica_Fluid_Valves_ValveDiscrete$valve_Medium_density MMC_REFSTRUCTLIT(boxvar_lit_Modelica_Fluid_Valves_ValveDiscrete$valve_Medium_density)


DLLExport
Modelica_Fluid_Valves_ValveDiscrete$valve_Medium_ThermodynamicState omc_Modelica_Fluid_Valves_ValveDiscrete$valve_Medium_ThermodynamicState(threadData_t *threadData, modelica_real p, modelica_real T); /* record head */

DLLExport
modelica_metatype boxptr_Modelica_Fluid_Valves_ValveDiscrete$valve_Medium_ThermodynamicState(threadData_t *threadData, modelica_metatype _p, modelica_metatype _T);
static const MMC_DEFSTRUCTLIT(boxvar_lit_Modelica_Fluid_Valves_ValveDiscrete$valve_Medium_ThermodynamicState,2,0) {(void*) boxptr_Modelica_Fluid_Valves_ValveDiscrete$valve_Medium_ThermodynamicState,0}};
#define boxvar_Modelica_Fluid_Valves_ValveDiscrete$valve_Medium_ThermodynamicState MMC_REFSTRUCTLIT(boxvar_lit_Modelica_Fluid_Valves_ValveDiscrete$valve_Medium_ThermodynamicState)


DLLExport
Modelica_Fluid_Vessels_BaseClasses_VesselPortsData omc_Modelica_Fluid_Vessels_BaseClasses_VesselPortsData(threadData_t *threadData, modelica_real diameter, modelica_real height, modelica_real zeta_out, modelica_real zeta_in); /* record head */

DLLExport
modelica_metatype boxptr_Modelica_Fluid_Vessels_BaseClasses_VesselPortsData(threadData_t *threadData, modelica_metatype _diameter, modelica_metatype _height, modelica_metatype _zeta_out, modelica_metatype _zeta_in);
static const MMC_DEFSTRUCTLIT(boxvar_lit_Modelica_Fluid_Vessels_BaseClasses_VesselPortsData,2,0) {(void*) boxptr_Modelica_Fluid_Vessels_BaseClasses_VesselPortsData,0}};
#define boxvar_Modelica_Fluid_Vessels_BaseClasses_VesselPortsData MMC_REFSTRUCTLIT(boxvar_lit_Modelica_Fluid_Vessels_BaseClasses_VesselPortsData)


DLLExport
modelica_real omc_Modelica_Fluid_Valves_ValveDiscrete$valve_Medium_temperature(threadData_t *threadData, Modelica_Fluid_Valves_ValveDiscrete$valve_Medium_ThermodynamicState _state);
DLLExport
modelica_metatype boxptr_Modelica_Fluid_Valves_ValveDiscrete$valve_Medium_temperature(threadData_t *threadData, modelica_metatype _state);
static const MMC_DEFSTRUCTLIT(boxvar_lit_Modelica_Fluid_Valves_ValveDiscrete$valve_Medium_temperature,2,0) {(void*) boxptr_Modelica_Fluid_Valves_ValveDiscrete$valve_Medium_temperature,0}};
#define boxvar_Modelica_Fluid_Valves_ValveDiscrete$valve_Medium_temperature MMC_REFSTRUCTLIT(boxvar_lit_Modelica_Fluid_Valves_ValveDiscrete$valve_Medium_temperature)


DLLExport
Modelica_Fluid_Valves_ValveDiscrete$valve_Medium_ThermodynamicState omc_Modelica_Fluid_Valves_ValveDiscrete$valve_Medium_setState__phX(threadData_t *threadData, modelica_real _p, modelica_real _h, real_array _X);
DLLExport
modelica_metatype boxptr_Modelica_Fluid_Valves_ValveDiscrete$valve_Medium_setState__phX(threadData_t *threadData, modelica_metatype _p, modelica_metatype _h, modelica_metatype _X);
static const MMC_DEFSTRUCTLIT(boxvar_lit_Modelica_Fluid_Valves_ValveDiscrete$valve_Medium_setState__phX,2,0) {(void*) boxptr_Modelica_Fluid_Valves_ValveDiscrete$valve_Medium_setState__phX,0}};
#define boxvar_Modelica_Fluid_Valves_ValveDiscrete$valve_Medium_setState__phX MMC_REFSTRUCTLIT(boxvar_lit_Modelica_Fluid_Valves_ValveDiscrete$valve_Medium_setState__phX)


DLLExport
Modelica_Fluid_Vessels_OpenTank$tank2_HeatTransfer$tank2$heatTransfer_Medium_FluidConstants omc_Modelica_Fluid_Vessels_OpenTank$tank2_HeatTransfer$tank2$heatTransfer_Medium_FluidConstants(threadData_t *threadData, modelica_string iupacName, modelica_string casRegistryNumber, modelica_string chemicalFormula, modelica_string structureFormula, modelica_real molarMass); /* record head */

DLLExport
modelica_metatype boxptr_Modelica_Fluid_Vessels_OpenTank$tank2_HeatTransfer$tank2$heatTransfer_Medium_FluidConstants(threadData_t *threadData, modelica_metatype _iupacName, modelica_metatype _casRegistryNumber, modelica_metatype _chemicalFormula, modelica_metatype _structureFormula, modelica_metatype _molarMass);
static const MMC_DEFSTRUCTLIT(boxvar_lit_Modelica_Fluid_Vessels_OpenTank$tank2_HeatTransfer$tank2$heatTransfer_Medium_FluidConstants,2,0) {(void*) boxptr_Modelica_Fluid_Vessels_OpenTank$tank2_HeatTransfer$tank2$heatTransfer_Medium_FluidConstants,0}};
#define boxvar_Modelica_Fluid_Vessels_OpenTank$tank2_HeatTransfer$tank2$heatTransfer_Medium_FluidConstants MMC_REFSTRUCTLIT(boxvar_lit_Modelica_Fluid_Vessels_OpenTank$tank2_HeatTransfer$tank2$heatTransfer_Medium_FluidConstants)


DLLExport
Modelica_Fluid_Vessels_OpenTank$tank1_Medium_FluidConstants omc_Modelica_Fluid_Vessels_OpenTank$tank1_Medium_FluidConstants(threadData_t *threadData, modelica_string iupacName, modelica_string casRegistryNumber, modelica_string chemicalFormula, modelica_string structureFormula, modelica_real molarMass); /* record head */

DLLExport
modelica_metatype boxptr_Modelica_Fluid_Vessels_OpenTank$tank1_Medium_FluidConstants(threadData_t *threadData, modelica_metatype _iupacName, modelica_metatype _casRegistryNumber, modelica_metatype _chemicalFormula, modelica_metatype _structureFormula, modelica_metatype _molarMass);
static const MMC_DEFSTRUCTLIT(boxvar_lit_Modelica_Fluid_Vessels_OpenTank$tank1_Medium_FluidConstants,2,0) {(void*) boxptr_Modelica_Fluid_Vessels_OpenTank$tank1_Medium_FluidConstants,0}};
#define boxvar_Modelica_Fluid_Vessels_OpenTank$tank1_Medium_FluidConstants MMC_REFSTRUCTLIT(boxvar_lit_Modelica_Fluid_Vessels_OpenTank$tank1_Medium_FluidConstants)


DLLExport
Modelica_Fluid_Vessels_OpenTank$tank1_HeatTransfer$tank1$heatTransfer_Medium_FluidConstants omc_Modelica_Fluid_Vessels_OpenTank$tank1_HeatTransfer$tank1$heatTransfer_Medium_FluidConstants(threadData_t *threadData, modelica_string iupacName, modelica_string casRegistryNumber, modelica_string chemicalFormula, modelica_string structureFormula, modelica_real molarMass); /* record head */

DLLExport
modelica_metatype boxptr_Modelica_Fluid_Vessels_OpenTank$tank1_HeatTransfer$tank1$heatTransfer_Medium_FluidConstants(threadData_t *threadData, modelica_metatype _iupacName, modelica_metatype _casRegistryNumber, modelica_metatype _chemicalFormula, modelica_metatype _structureFormula, modelica_metatype _molarMass);
static const MMC_DEFSTRUCTLIT(boxvar_lit_Modelica_Fluid_Vessels_OpenTank$tank1_HeatTransfer$tank1$heatTransfer_Medium_FluidConstants,2,0) {(void*) boxptr_Modelica_Fluid_Vessels_OpenTank$tank1_HeatTransfer$tank1$heatTransfer_Medium_FluidConstants,0}};
#define boxvar_Modelica_Fluid_Vessels_OpenTank$tank1_HeatTransfer$tank1$heatTransfer_Medium_FluidConstants MMC_REFSTRUCTLIT(boxvar_lit_Modelica_Fluid_Vessels_OpenTank$tank1_HeatTransfer$tank1$heatTransfer_Medium_FluidConstants)


DLLExport
Modelica_Fluid_Vessels_BaseClasses_VesselFluidPorts__b$tank2$ports_Medium_FluidConstants omc_Modelica_Fluid_Vessels_BaseClasses_VesselFluidPorts__b$tank2$ports_Medium_FluidConstants(threadData_t *threadData, modelica_string iupacName, modelica_string casRegistryNumber, modelica_string chemicalFormula, modelica_string structureFormula, modelica_real molarMass); /* record head */

DLLExport
modelica_metatype boxptr_Modelica_Fluid_Vessels_BaseClasses_VesselFluidPorts__b$tank2$ports_Medium_FluidConstants(threadData_t *threadData, modelica_metatype _iupacName, modelica_metatype _casRegistryNumber, modelica_metatype _chemicalFormula, modelica_metatype _structureFormula, modelica_metatype _molarMass);
static const MMC_DEFSTRUCTLIT(boxvar_lit_Modelica_Fluid_Vessels_BaseClasses_VesselFluidPorts__b$tank2$ports_Medium_FluidConstants,2,0) {(void*) boxptr_Modelica_Fluid_Vessels_BaseClasses_VesselFluidPorts__b$tank2$ports_Medium_FluidConstants,0}};
#define boxvar_Modelica_Fluid_Vessels_BaseClasses_VesselFluidPorts__b$tank2$ports_Medium_FluidConstants MMC_REFSTRUCTLIT(boxvar_lit_Modelica_Fluid_Vessels_BaseClasses_VesselFluidPorts__b$tank2$ports_Medium_FluidConstants)


DLLExport
Modelica_Fluid_Vessels_OpenTank$tank1_HeatTransfer$tank1$heatTransfer_Medium_ThermodynamicState omc_Modelica_Fluid_Vessels_OpenTank$tank1_HeatTransfer$tank1$heatTransfer_Medium_ThermodynamicState(threadData_t *threadData, modelica_real p, modelica_real T); /* record head */

DLLExport
modelica_metatype boxptr_Modelica_Fluid_Vessels_OpenTank$tank1_HeatTransfer$tank1$heatTransfer_Medium_ThermodynamicState(threadData_t *threadData, modelica_metatype _p, modelica_metatype _T);
static const MMC_DEFSTRUCTLIT(boxvar_lit_Modelica_Fluid_Vessels_OpenTank$tank1_HeatTransfer$tank1$heatTransfer_Medium_ThermodynamicState,2,0) {(void*) boxptr_Modelica_Fluid_Vessels_OpenTank$tank1_HeatTransfer$tank1$heatTransfer_Medium_ThermodynamicState,0}};
#define boxvar_Modelica_Fluid_Vessels_OpenTank$tank1_HeatTransfer$tank1$heatTransfer_Medium_ThermodynamicState MMC_REFSTRUCTLIT(boxvar_lit_Modelica_Fluid_Vessels_OpenTank$tank1_HeatTransfer$tank1$heatTransfer_Medium_ThermodynamicState)


DLLExport
modelica_real omc_Modelica_Fluid_Vessels_OpenTank$tank1_HeatTransfer$tank1$heatTransfer_Medium_temperature(threadData_t *threadData, Modelica_Fluid_Vessels_OpenTank$tank1_HeatTransfer$tank1$heatTransfer_Medium_ThermodynamicState _state);
DLLExport
modelica_metatype boxptr_Modelica_Fluid_Vessels_OpenTank$tank1_HeatTransfer$tank1$heatTransfer_Medium_temperature(threadData_t *threadData, modelica_metatype _state);
static const MMC_DEFSTRUCTLIT(boxvar_lit_Modelica_Fluid_Vessels_OpenTank$tank1_HeatTransfer$tank1$heatTransfer_Medium_temperature,2,0) {(void*) boxptr_Modelica_Fluid_Vessels_OpenTank$tank1_HeatTransfer$tank1$heatTransfer_Medium_temperature,0}};
#define boxvar_Modelica_Fluid_Vessels_OpenTank$tank1_HeatTransfer$tank1$heatTransfer_Medium_temperature MMC_REFSTRUCTLIT(boxvar_lit_Modelica_Fluid_Vessels_OpenTank$tank1_HeatTransfer$tank1$heatTransfer_Medium_temperature)


DLLExport
Modelica_Fluid_Vessels_OpenTank$tank1_Medium_ThermodynamicState omc_Modelica_Fluid_Vessels_OpenTank$tank1_Medium_setState__phX(threadData_t *threadData, modelica_real _p, modelica_real _h, real_array _X);
DLLExport
modelica_metatype boxptr_Modelica_Fluid_Vessels_OpenTank$tank1_Medium_setState__phX(threadData_t *threadData, modelica_metatype _p, modelica_metatype _h, modelica_metatype _X);
static const MMC_DEFSTRUCTLIT(boxvar_lit_Modelica_Fluid_Vessels_OpenTank$tank1_Medium_setState__phX,2,0) {(void*) boxptr_Modelica_Fluid_Vessels_OpenTank$tank1_Medium_setState__phX,0}};
#define boxvar_Modelica_Fluid_Vessels_OpenTank$tank1_Medium_setState__phX MMC_REFSTRUCTLIT(boxvar_lit_Modelica_Fluid_Vessels_OpenTank$tank1_Medium_setState__phX)


DLLExport
Modelica_Fluid_Vessels_OpenTank$tank1_Medium_ThermodynamicState omc_Modelica_Fluid_Vessels_OpenTank$tank1_Medium_ThermodynamicState(threadData_t *threadData, modelica_real p, modelica_real T); /* record head */

DLLExport
modelica_metatype boxptr_Modelica_Fluid_Vessels_OpenTank$tank1_Medium_ThermodynamicState(threadData_t *threadData, modelica_metatype _p, modelica_metatype _T);
static const MMC_DEFSTRUCTLIT(boxvar_lit_Modelica_Fluid_Vessels_OpenTank$tank1_Medium_ThermodynamicState,2,0) {(void*) boxptr_Modelica_Fluid_Vessels_OpenTank$tank1_Medium_ThermodynamicState,0}};
#define boxvar_Modelica_Fluid_Vessels_OpenTank$tank1_Medium_ThermodynamicState MMC_REFSTRUCTLIT(boxvar_lit_Modelica_Fluid_Vessels_OpenTank$tank1_Medium_ThermodynamicState)


DLLExport
modelica_real omc_Modelica_Fluid_Vessels_OpenTank$tank1_Medium_density(threadData_t *threadData, Modelica_Fluid_Vessels_OpenTank$tank1_Medium_ThermodynamicState _state);
DLLExport
modelica_metatype boxptr_Modelica_Fluid_Vessels_OpenTank$tank1_Medium_density(threadData_t *threadData, modelica_metatype _state);
static const MMC_DEFSTRUCTLIT(boxvar_lit_Modelica_Fluid_Vessels_OpenTank$tank1_Medium_density,2,0) {(void*) boxptr_Modelica_Fluid_Vessels_OpenTank$tank1_Medium_density,0}};
#define boxvar_Modelica_Fluid_Vessels_OpenTank$tank1_Medium_density MMC_REFSTRUCTLIT(boxvar_lit_Modelica_Fluid_Vessels_OpenTank$tank1_Medium_density)


DLLExport
modelica_real omc_Modelica_Fluid_Vessels_OpenTank$tank1_Medium_specificEnthalpy__pTX(threadData_t *threadData, modelica_real _p, modelica_real _T, real_array _X);
DLLExport
modelica_metatype boxptr_Modelica_Fluid_Vessels_OpenTank$tank1_Medium_specificEnthalpy__pTX(threadData_t *threadData, modelica_metatype _p, modelica_metatype _T, modelica_metatype _X);
static const MMC_DEFSTRUCTLIT(boxvar_lit_Modelica_Fluid_Vessels_OpenTank$tank1_Medium_specificEnthalpy__pTX,2,0) {(void*) boxptr_Modelica_Fluid_Vessels_OpenTank$tank1_Medium_specificEnthalpy__pTX,0}};
#define boxvar_Modelica_Fluid_Vessels_OpenTank$tank1_Medium_specificEnthalpy__pTX MMC_REFSTRUCTLIT(boxvar_lit_Modelica_Fluid_Vessels_OpenTank$tank1_Medium_specificEnthalpy__pTX)


DLLExport
Modelica_Fluid_Vessels_OpenTank$tank2_Medium_ThermodynamicState omc_Modelica_Fluid_Vessels_OpenTank$tank2_Medium_ThermodynamicState(threadData_t *threadData, modelica_real p, modelica_real T); /* record head */

DLLExport
modelica_metatype boxptr_Modelica_Fluid_Vessels_OpenTank$tank2_Medium_ThermodynamicState(threadData_t *threadData, modelica_metatype _p, modelica_metatype _T);
static const MMC_DEFSTRUCTLIT(boxvar_lit_Modelica_Fluid_Vessels_OpenTank$tank2_Medium_ThermodynamicState,2,0) {(void*) boxptr_Modelica_Fluid_Vessels_OpenTank$tank2_Medium_ThermodynamicState,0}};
#define boxvar_Modelica_Fluid_Vessels_OpenTank$tank2_Medium_ThermodynamicState MMC_REFSTRUCTLIT(boxvar_lit_Modelica_Fluid_Vessels_OpenTank$tank2_Medium_ThermodynamicState)


DLLExport
modelica_real omc_Modelica_Fluid_Vessels_OpenTank$tank2_HeatTransfer$tank2$heatTransfer_Medium_temperature(threadData_t *threadData, Modelica_Fluid_Vessels_OpenTank$tank2_HeatTransfer$tank2$heatTransfer_Medium_ThermodynamicState _state);
DLLExport
modelica_metatype boxptr_Modelica_Fluid_Vessels_OpenTank$tank2_HeatTransfer$tank2$heatTransfer_Medium_temperature(threadData_t *threadData, modelica_metatype _state);
static const MMC_DEFSTRUCTLIT(boxvar_lit_Modelica_Fluid_Vessels_OpenTank$tank2_HeatTransfer$tank2$heatTransfer_Medium_temperature,2,0) {(void*) boxptr_Modelica_Fluid_Vessels_OpenTank$tank2_HeatTransfer$tank2$heatTransfer_Medium_temperature,0}};
#define boxvar_Modelica_Fluid_Vessels_OpenTank$tank2_HeatTransfer$tank2$heatTransfer_Medium_temperature MMC_REFSTRUCTLIT(boxvar_lit_Modelica_Fluid_Vessels_OpenTank$tank2_HeatTransfer$tank2$heatTransfer_Medium_temperature)


DLLExport
Modelica_Fluid_Vessels_OpenTank$tank2_HeatTransfer$tank2$heatTransfer_Medium_ThermodynamicState omc_Modelica_Fluid_Vessels_OpenTank$tank2_HeatTransfer$tank2$heatTransfer_Medium_ThermodynamicState(threadData_t *threadData, modelica_real p, modelica_real T); /* record head */

DLLExport
modelica_metatype boxptr_Modelica_Fluid_Vessels_OpenTank$tank2_HeatTransfer$tank2$heatTransfer_Medium_ThermodynamicState(threadData_t *threadData, modelica_metatype _p, modelica_metatype _T);
static const MMC_DEFSTRUCTLIT(boxvar_lit_Modelica_Fluid_Vessels_OpenTank$tank2_HeatTransfer$tank2$heatTransfer_Medium_ThermodynamicState,2,0) {(void*) boxptr_Modelica_Fluid_Vessels_OpenTank$tank2_HeatTransfer$tank2$heatTransfer_Medium_ThermodynamicState,0}};
#define boxvar_Modelica_Fluid_Vessels_OpenTank$tank2_HeatTransfer$tank2$heatTransfer_Medium_ThermodynamicState MMC_REFSTRUCTLIT(boxvar_lit_Modelica_Fluid_Vessels_OpenTank$tank2_HeatTransfer$tank2$heatTransfer_Medium_ThermodynamicState)


DLLExport
Modelica_Fluid_Vessels_OpenTank$tank2_Medium_FluidConstants omc_Modelica_Fluid_Vessels_OpenTank$tank2_Medium_FluidConstants(threadData_t *threadData, modelica_string iupacName, modelica_string casRegistryNumber, modelica_string chemicalFormula, modelica_string structureFormula, modelica_real molarMass); /* record head */

DLLExport
modelica_metatype boxptr_Modelica_Fluid_Vessels_OpenTank$tank2_Medium_FluidConstants(threadData_t *threadData, modelica_metatype _iupacName, modelica_metatype _casRegistryNumber, modelica_metatype _chemicalFormula, modelica_metatype _structureFormula, modelica_metatype _molarMass);
static const MMC_DEFSTRUCTLIT(boxvar_lit_Modelica_Fluid_Vessels_OpenTank$tank2_Medium_FluidConstants,2,0) {(void*) boxptr_Modelica_Fluid_Vessels_OpenTank$tank2_Medium_FluidConstants,0}};
#define boxvar_Modelica_Fluid_Vessels_OpenTank$tank2_Medium_FluidConstants MMC_REFSTRUCTLIT(boxvar_lit_Modelica_Fluid_Vessels_OpenTank$tank2_Medium_FluidConstants)


DLLExport
Modelica_Media_Interfaces_Types_Basic_FluidConstants$simpleWaterConstants omc_Modelica_Media_Interfaces_Types_Basic_FluidConstants$simpleWaterConstants(threadData_t *threadData, modelica_string iupacName, modelica_string casRegistryNumber, modelica_string chemicalFormula, modelica_string structureFormula, modelica_real molarMass); /* record head */

DLLExport
modelica_metatype boxptr_Modelica_Media_Interfaces_Types_Basic_FluidConstants$simpleWaterConstants(threadData_t *threadData, modelica_metatype _iupacName, modelica_metatype _casRegistryNumber, modelica_metatype _chemicalFormula, modelica_metatype _structureFormula, modelica_metatype _molarMass);
static const MMC_DEFSTRUCTLIT(boxvar_lit_Modelica_Media_Interfaces_Types_Basic_FluidConstants$simpleWaterConstants,2,0) {(void*) boxptr_Modelica_Media_Interfaces_Types_Basic_FluidConstants$simpleWaterConstants,0}};
#define boxvar_Modelica_Media_Interfaces_Types_Basic_FluidConstants$simpleWaterConstants MMC_REFSTRUCTLIT(boxvar_lit_Modelica_Media_Interfaces_Types_Basic_FluidConstants$simpleWaterConstants)


DLLExport
Modelica_Media_Interfaces_Types_Basic_FluidConstants omc_Modelica_Media_Interfaces_Types_Basic_FluidConstants(threadData_t *threadData, modelica_string iupacName, modelica_string casRegistryNumber, modelica_string chemicalFormula, modelica_string structureFormula, modelica_real molarMass); /* record head */

DLLExport
modelica_metatype boxptr_Modelica_Media_Interfaces_Types_Basic_FluidConstants(threadData_t *threadData, modelica_metatype _iupacName, modelica_metatype _casRegistryNumber, modelica_metatype _chemicalFormula, modelica_metatype _structureFormula, modelica_metatype _molarMass);
static const MMC_DEFSTRUCTLIT(boxvar_lit_Modelica_Media_Interfaces_Types_Basic_FluidConstants,2,0) {(void*) boxptr_Modelica_Media_Interfaces_Types_Basic_FluidConstants,0}};
#define boxvar_Modelica_Media_Interfaces_Types_Basic_FluidConstants MMC_REFSTRUCTLIT(boxvar_lit_Modelica_Media_Interfaces_Types_Basic_FluidConstants)


DLLExport
modelica_real omc_Modelica_Fluid_Vessels_OpenTank$tank2_Medium_specificEnthalpy__pTX(threadData_t *threadData, modelica_real _p, modelica_real _T, real_array _X);
DLLExport
modelica_metatype boxptr_Modelica_Fluid_Vessels_OpenTank$tank2_Medium_specificEnthalpy__pTX(threadData_t *threadData, modelica_metatype _p, modelica_metatype _T, modelica_metatype _X);
static const MMC_DEFSTRUCTLIT(boxvar_lit_Modelica_Fluid_Vessels_OpenTank$tank2_Medium_specificEnthalpy__pTX,2,0) {(void*) boxptr_Modelica_Fluid_Vessels_OpenTank$tank2_Medium_specificEnthalpy__pTX,0}};
#define boxvar_Modelica_Fluid_Vessels_OpenTank$tank2_Medium_specificEnthalpy__pTX MMC_REFSTRUCTLIT(boxvar_lit_Modelica_Fluid_Vessels_OpenTank$tank2_Medium_specificEnthalpy__pTX)


DLLExport
Modelica_Fluid_Vessels_OpenTank$tank2_Medium_ThermodynamicState omc_Modelica_Fluid_Vessels_OpenTank$tank2_Medium_setState__phX(threadData_t *threadData, modelica_real _p, modelica_real _h, real_array _X);
DLLExport
modelica_metatype boxptr_Modelica_Fluid_Vessels_OpenTank$tank2_Medium_setState__phX(threadData_t *threadData, modelica_metatype _p, modelica_metatype _h, modelica_metatype _X);
static const MMC_DEFSTRUCTLIT(boxvar_lit_Modelica_Fluid_Vessels_OpenTank$tank2_Medium_setState__phX,2,0) {(void*) boxptr_Modelica_Fluid_Vessels_OpenTank$tank2_Medium_setState__phX,0}};
#define boxvar_Modelica_Fluid_Vessels_OpenTank$tank2_Medium_setState__phX MMC_REFSTRUCTLIT(boxvar_lit_Modelica_Fluid_Vessels_OpenTank$tank2_Medium_setState__phX)


DLLExport
modelica_real omc_Modelica_Fluid_Vessels_OpenTank$tank2_Medium_density(threadData_t *threadData, Modelica_Fluid_Vessels_OpenTank$tank2_Medium_ThermodynamicState _state);
DLLExport
modelica_metatype boxptr_Modelica_Fluid_Vessels_OpenTank$tank2_Medium_density(threadData_t *threadData, modelica_metatype _state);
static const MMC_DEFSTRUCTLIT(boxvar_lit_Modelica_Fluid_Vessels_OpenTank$tank2_Medium_density,2,0) {(void*) boxptr_Modelica_Fluid_Vessels_OpenTank$tank2_Medium_density,0}};
#define boxvar_Modelica_Fluid_Vessels_OpenTank$tank2_Medium_density MMC_REFSTRUCTLIT(boxvar_lit_Modelica_Fluid_Vessels_OpenTank$tank2_Medium_density)
#include "PipesValveDiscrete_model.h"


#ifdef __cplusplus
}
#endif
#endif

