/* Additional record code for PipesValveDiscrete generated by the OpenModelica Compiler OpenModelica 1.9.3. */

#include "meta/meta_modelica.h"

#ifdef __cplusplus
extern "C" {
#endif

#define Modelica_Fluid_Vessels_BaseClasses_VesselFluidPorts__b$tank1$ports_Medium_FluidConstants__desc_added 1
const char* Modelica_Fluid_Vessels_BaseClasses_VesselFluidPorts__b$tank1$ports_Medium_FluidConstants__desc__fields[5] = {"_casRegistryNumber","_chemicalFormula","_iupacName","_molarMass","_structureFormula"};
struct record_description Modelica_Fluid_Vessels_BaseClasses_VesselFluidPorts__b$tank1$ports_Medium_FluidConstants__desc = {
  "Modelica_Fluid_Vessels_BaseClasses_VesselFluidPorts__b$tank1$ports_Medium_FluidConstants", /* package_record__X */
  "Modelica.Fluid.Vessels.BaseClasses.VesselFluidPorts_b$tank1$ports.Medium.FluidConstants", /* package.record_X */
  Modelica_Fluid_Vessels_BaseClasses_VesselFluidPorts__b$tank1$ports_Medium_FluidConstants__desc__fields
};

#define Modelica_Fluid_Pipes_StaticPipe$pipe_FlowModel$pipe$flowModel_Medium_ThermodynamicState__desc_added 1
const char* Modelica_Fluid_Pipes_StaticPipe$pipe_FlowModel$pipe$flowModel_Medium_ThermodynamicState__desc__fields[2] = {"_T","_p"};
struct record_description Modelica_Fluid_Pipes_StaticPipe$pipe_FlowModel$pipe$flowModel_Medium_ThermodynamicState__desc = {
  "Modelica_Fluid_Pipes_StaticPipe$pipe_FlowModel$pipe$flowModel_Medium_ThermodynamicState", /* package_record__X */
  "Modelica.Fluid.Pipes.StaticPipe$pipe.FlowModel$pipe$flowModel.Medium.ThermodynamicState", /* package.record_X */
  Modelica_Fluid_Pipes_StaticPipe$pipe_FlowModel$pipe$flowModel_Medium_ThermodynamicState__desc__fields
};

#define Modelica_Fluid_Vessels_BaseClasses_VesselPortsData__desc_added 1
const char* Modelica_Fluid_Vessels_BaseClasses_VesselPortsData__desc__fields[4] = {"_diameter","_height","_zeta_in","_zeta_out"};
struct record_description Modelica_Fluid_Vessels_BaseClasses_VesselPortsData__desc = {
  "Modelica_Fluid_Vessels_BaseClasses_VesselPortsData", /* package_record__X */
  "Modelica.Fluid.Vessels.BaseClasses.VesselPortsData", /* package.record_X */
  Modelica_Fluid_Vessels_BaseClasses_VesselPortsData__desc__fields
};

#define Modelica_Fluid_Pipes_StaticPipe$pipe_FlowModel$pipe$flowModel_Medium_FluidConstants__desc_added 1
const char* Modelica_Fluid_Pipes_StaticPipe$pipe_FlowModel$pipe$flowModel_Medium_FluidConstants__desc__fields[5] = {"_casRegistryNumber","_chemicalFormula","_iupacName","_molarMass","_structureFormula"};
struct record_description Modelica_Fluid_Pipes_StaticPipe$pipe_FlowModel$pipe$flowModel_Medium_FluidConstants__desc = {
  "Modelica_Fluid_Pipes_StaticPipe$pipe_FlowModel$pipe$flowModel_Medium_FluidConstants", /* package_record__X */
  "Modelica.Fluid.Pipes.StaticPipe$pipe.FlowModel$pipe$flowModel.Medium.FluidConstants", /* package.record_X */
  Modelica_Fluid_Pipes_StaticPipe$pipe_FlowModel$pipe$flowModel_Medium_FluidConstants__desc__fields
};

#define Modelica_Fluid_Interfaces_FluidPort__b$pipe$port__b_Medium_FluidConstants__desc_added 1
const char* Modelica_Fluid_Interfaces_FluidPort__b$pipe$port__b_Medium_FluidConstants__desc__fields[5] = {"_casRegistryNumber","_chemicalFormula","_iupacName","_molarMass","_structureFormula"};
struct record_description Modelica_Fluid_Interfaces_FluidPort__b$pipe$port__b_Medium_FluidConstants__desc = {
  "Modelica_Fluid_Interfaces_FluidPort__b$pipe$port__b_Medium_FluidConstants", /* package_record__X */
  "Modelica.Fluid.Interfaces.FluidPort_b$pipe$port_b.Medium.FluidConstants", /* package.record_X */
  Modelica_Fluid_Interfaces_FluidPort__b$pipe$port__b_Medium_FluidConstants__desc__fields
};

#define Modelica_Fluid_Interfaces_FluidPort__a$valve$port__a_Medium_FluidConstants__desc_added 1
const char* Modelica_Fluid_Interfaces_FluidPort__a$valve$port__a_Medium_FluidConstants__desc__fields[5] = {"_casRegistryNumber","_chemicalFormula","_iupacName","_molarMass","_structureFormula"};
struct record_description Modelica_Fluid_Interfaces_FluidPort__a$valve$port__a_Medium_FluidConstants__desc = {
  "Modelica_Fluid_Interfaces_FluidPort__a$valve$port__a_Medium_FluidConstants", /* package_record__X */
  "Modelica.Fluid.Interfaces.FluidPort_a$valve$port_a.Medium.FluidConstants", /* package.record_X */
  Modelica_Fluid_Interfaces_FluidPort__a$valve$port__a_Medium_FluidConstants__desc__fields
};

#define Modelica_Fluid_Interfaces_FluidPort__a$pipe$port__a_Medium_FluidConstants__desc_added 1
const char* Modelica_Fluid_Interfaces_FluidPort__a$pipe$port__a_Medium_FluidConstants__desc__fields[5] = {"_casRegistryNumber","_chemicalFormula","_iupacName","_molarMass","_structureFormula"};
struct record_description Modelica_Fluid_Interfaces_FluidPort__a$pipe$port__a_Medium_FluidConstants__desc = {
  "Modelica_Fluid_Interfaces_FluidPort__a$pipe$port__a_Medium_FluidConstants", /* package_record__X */
  "Modelica.Fluid.Interfaces.FluidPort_a$pipe$port_a.Medium.FluidConstants", /* package.record_X */
  Modelica_Fluid_Interfaces_FluidPort__a$pipe$port__a_Medium_FluidConstants__desc__fields
};

#define Modelica_Fluid_Interfaces_FluidPort__b$valve$port__b_Medium_FluidConstants__desc_added 1
const char* Modelica_Fluid_Interfaces_FluidPort__b$valve$port__b_Medium_FluidConstants__desc__fields[5] = {"_casRegistryNumber","_chemicalFormula","_iupacName","_molarMass","_structureFormula"};
struct record_description Modelica_Fluid_Interfaces_FluidPort__b$valve$port__b_Medium_FluidConstants__desc = {
  "Modelica_Fluid_Interfaces_FluidPort__b$valve$port__b_Medium_FluidConstants", /* package_record__X */
  "Modelica.Fluid.Interfaces.FluidPort_b$valve$port_b.Medium.FluidConstants", /* package.record_X */
  Modelica_Fluid_Interfaces_FluidPort__b$valve$port__b_Medium_FluidConstants__desc__fields
};

#define Modelica_Fluid_Pipes_StaticPipe$pipe_Medium_FluidConstants__desc_added 1
const char* Modelica_Fluid_Pipes_StaticPipe$pipe_Medium_FluidConstants__desc__fields[5] = {"_casRegistryNumber","_chemicalFormula","_iupacName","_molarMass","_structureFormula"};
struct record_description Modelica_Fluid_Pipes_StaticPipe$pipe_Medium_FluidConstants__desc = {
  "Modelica_Fluid_Pipes_StaticPipe$pipe_Medium_FluidConstants", /* package_record__X */
  "Modelica.Fluid.Pipes.StaticPipe$pipe.Medium.FluidConstants", /* package.record_X */
  Modelica_Fluid_Pipes_StaticPipe$pipe_Medium_FluidConstants__desc__fields
};

#define Modelica_Fluid_Valves_ValveDiscrete$valve_Medium_FluidConstants__desc_added 1
const char* Modelica_Fluid_Valves_ValveDiscrete$valve_Medium_FluidConstants__desc__fields[5] = {"_casRegistryNumber","_chemicalFormula","_iupacName","_molarMass","_structureFormula"};
struct record_description Modelica_Fluid_Valves_ValveDiscrete$valve_Medium_FluidConstants__desc = {
  "Modelica_Fluid_Valves_ValveDiscrete$valve_Medium_FluidConstants", /* package_record__X */
  "Modelica.Fluid.Valves.ValveDiscrete$valve.Medium.FluidConstants", /* package.record_X */
  Modelica_Fluid_Valves_ValveDiscrete$valve_Medium_FluidConstants__desc__fields
};

#define Modelica_Fluid_Vessels_OpenTank$tank2_HeatTransfer$tank2$heatTransfer_Medium_FluidConstants__desc_added 1
const char* Modelica_Fluid_Vessels_OpenTank$tank2_HeatTransfer$tank2$heatTransfer_Medium_FluidConstants__desc__fields[5] = {"_casRegistryNumber","_chemicalFormula","_iupacName","_molarMass","_structureFormula"};
struct record_description Modelica_Fluid_Vessels_OpenTank$tank2_HeatTransfer$tank2$heatTransfer_Medium_FluidConstants__desc = {
  "Modelica_Fluid_Vessels_OpenTank$tank2_HeatTransfer$tank2$heatTransfer_Medium_FluidConstants", /* package_record__X */
  "Modelica.Fluid.Vessels.OpenTank$tank2.HeatTransfer$tank2$heatTransfer.Medium.FluidConstants", /* package.record_X */
  Modelica_Fluid_Vessels_OpenTank$tank2_HeatTransfer$tank2$heatTransfer_Medium_FluidConstants__desc__fields
};

#define Modelica_Fluid_Vessels_OpenTank$tank1_Medium_FluidConstants__desc_added 1
const char* Modelica_Fluid_Vessels_OpenTank$tank1_Medium_FluidConstants__desc__fields[5] = {"_casRegistryNumber","_chemicalFormula","_iupacName","_molarMass","_structureFormula"};
struct record_description Modelica_Fluid_Vessels_OpenTank$tank1_Medium_FluidConstants__desc = {
  "Modelica_Fluid_Vessels_OpenTank$tank1_Medium_FluidConstants", /* package_record__X */
  "Modelica.Fluid.Vessels.OpenTank$tank1.Medium.FluidConstants", /* package.record_X */
  Modelica_Fluid_Vessels_OpenTank$tank1_Medium_FluidConstants__desc__fields
};

#define Modelica_Fluid_Vessels_OpenTank$tank1_HeatTransfer$tank1$heatTransfer_Medium_FluidConstants__desc_added 1
const char* Modelica_Fluid_Vessels_OpenTank$tank1_HeatTransfer$tank1$heatTransfer_Medium_FluidConstants__desc__fields[5] = {"_casRegistryNumber","_chemicalFormula","_iupacName","_molarMass","_structureFormula"};
struct record_description Modelica_Fluid_Vessels_OpenTank$tank1_HeatTransfer$tank1$heatTransfer_Medium_FluidConstants__desc = {
  "Modelica_Fluid_Vessels_OpenTank$tank1_HeatTransfer$tank1$heatTransfer_Medium_FluidConstants", /* package_record__X */
  "Modelica.Fluid.Vessels.OpenTank$tank1.HeatTransfer$tank1$heatTransfer.Medium.FluidConstants", /* package.record_X */
  Modelica_Fluid_Vessels_OpenTank$tank1_HeatTransfer$tank1$heatTransfer_Medium_FluidConstants__desc__fields
};

#define Modelica_Fluid_Vessels_BaseClasses_VesselFluidPorts__b$tank2$ports_Medium_FluidConstants__desc_added 1
const char* Modelica_Fluid_Vessels_BaseClasses_VesselFluidPorts__b$tank2$ports_Medium_FluidConstants__desc__fields[5] = {"_casRegistryNumber","_chemicalFormula","_iupacName","_molarMass","_structureFormula"};
struct record_description Modelica_Fluid_Vessels_BaseClasses_VesselFluidPorts__b$tank2$ports_Medium_FluidConstants__desc = {
  "Modelica_Fluid_Vessels_BaseClasses_VesselFluidPorts__b$tank2$ports_Medium_FluidConstants", /* package_record__X */
  "Modelica.Fluid.Vessels.BaseClasses.VesselFluidPorts_b$tank2$ports.Medium.FluidConstants", /* package.record_X */
  Modelica_Fluid_Vessels_BaseClasses_VesselFluidPorts__b$tank2$ports_Medium_FluidConstants__desc__fields
};

#define Modelica_Fluid_Vessels_OpenTank$tank2_Medium_FluidConstants__desc_added 1
const char* Modelica_Fluid_Vessels_OpenTank$tank2_Medium_FluidConstants__desc__fields[5] = {"_casRegistryNumber","_chemicalFormula","_iupacName","_molarMass","_structureFormula"};
struct record_description Modelica_Fluid_Vessels_OpenTank$tank2_Medium_FluidConstants__desc = {
  "Modelica_Fluid_Vessels_OpenTank$tank2_Medium_FluidConstants", /* package_record__X */
  "Modelica.Fluid.Vessels.OpenTank$tank2.Medium.FluidConstants", /* package.record_X */
  Modelica_Fluid_Vessels_OpenTank$tank2_Medium_FluidConstants__desc__fields
};

#define Modelica_Media_Interfaces_Types_Basic_FluidConstants$simpleWaterConstants__desc_added 1
const char* Modelica_Media_Interfaces_Types_Basic_FluidConstants$simpleWaterConstants__desc__fields[5] = {"_casRegistryNumber","_chemicalFormula","_iupacName","_molarMass","_structureFormula"};
struct record_description Modelica_Media_Interfaces_Types_Basic_FluidConstants$simpleWaterConstants__desc = {
  "Modelica_Media_Interfaces_Types_Basic_FluidConstants$simpleWaterConstants", /* package_record__X */
  "Modelica.Media.Interfaces.Types.Basic.FluidConstants$simpleWaterConstants", /* package.record_X */
  Modelica_Media_Interfaces_Types_Basic_FluidConstants$simpleWaterConstants__desc__fields
};

#define Modelica_Media_Interfaces_Types_Basic_FluidConstants__desc_added 1
const char* Modelica_Media_Interfaces_Types_Basic_FluidConstants__desc__fields[5] = {"_casRegistryNumber","_chemicalFormula","_iupacName","_molarMass","_structureFormula"};
struct record_description Modelica_Media_Interfaces_Types_Basic_FluidConstants__desc = {
  "Modelica_Media_Interfaces_Types_Basic_FluidConstants", /* package_record__X */
  "Modelica.Media.Interfaces.Types.Basic.FluidConstants", /* package.record_X */
  Modelica_Media_Interfaces_Types_Basic_FluidConstants__desc__fields
};

#define Modelica_Fluid_Pipes_StaticPipe$pipe_Medium_ThermodynamicState__desc_added 1
const char* Modelica_Fluid_Pipes_StaticPipe$pipe_Medium_ThermodynamicState__desc__fields[2] = {"_T","_p"};
struct record_description Modelica_Fluid_Pipes_StaticPipe$pipe_Medium_ThermodynamicState__desc = {
  "Modelica_Fluid_Pipes_StaticPipe$pipe_Medium_ThermodynamicState", /* package_record__X */
  "Modelica.Fluid.Pipes.StaticPipe$pipe.Medium.ThermodynamicState", /* package.record_X */
  Modelica_Fluid_Pipes_StaticPipe$pipe_Medium_ThermodynamicState__desc__fields
};

#define Modelica_Fluid_Valves_ValveDiscrete$valve_Medium_ThermodynamicState__desc_added 1
const char* Modelica_Fluid_Valves_ValveDiscrete$valve_Medium_ThermodynamicState__desc__fields[2] = {"_T","_p"};
struct record_description Modelica_Fluid_Valves_ValveDiscrete$valve_Medium_ThermodynamicState__desc = {
  "Modelica_Fluid_Valves_ValveDiscrete$valve_Medium_ThermodynamicState", /* package_record__X */
  "Modelica.Fluid.Valves.ValveDiscrete$valve.Medium.ThermodynamicState", /* package.record_X */
  Modelica_Fluid_Valves_ValveDiscrete$valve_Medium_ThermodynamicState__desc__fields
};

#define Modelica_Fluid_Vessels_OpenTank$tank1_HeatTransfer$tank1$heatTransfer_Medium_ThermodynamicState__desc_added 1
const char* Modelica_Fluid_Vessels_OpenTank$tank1_HeatTransfer$tank1$heatTransfer_Medium_ThermodynamicState__desc__fields[2] = {"_T","_p"};
struct record_description Modelica_Fluid_Vessels_OpenTank$tank1_HeatTransfer$tank1$heatTransfer_Medium_ThermodynamicState__desc = {
  "Modelica_Fluid_Vessels_OpenTank$tank1_HeatTransfer$tank1$heatTransfer_Medium_ThermodynamicState", /* package_record__X */
  "Modelica.Fluid.Vessels.OpenTank$tank1.HeatTransfer$tank1$heatTransfer.Medium.ThermodynamicState", /* package.record_X */
  Modelica_Fluid_Vessels_OpenTank$tank1_HeatTransfer$tank1$heatTransfer_Medium_ThermodynamicState__desc__fields
};

#define Modelica_Fluid_Vessels_OpenTank$tank1_Medium_ThermodynamicState__desc_added 1
const char* Modelica_Fluid_Vessels_OpenTank$tank1_Medium_ThermodynamicState__desc__fields[2] = {"_T","_p"};
struct record_description Modelica_Fluid_Vessels_OpenTank$tank1_Medium_ThermodynamicState__desc = {
  "Modelica_Fluid_Vessels_OpenTank$tank1_Medium_ThermodynamicState", /* package_record__X */
  "Modelica.Fluid.Vessels.OpenTank$tank1.Medium.ThermodynamicState", /* package.record_X */
  Modelica_Fluid_Vessels_OpenTank$tank1_Medium_ThermodynamicState__desc__fields
};

#define Modelica_Fluid_Vessels_OpenTank$tank2_Medium_ThermodynamicState__desc_added 1
const char* Modelica_Fluid_Vessels_OpenTank$tank2_Medium_ThermodynamicState__desc__fields[2] = {"_T","_p"};
struct record_description Modelica_Fluid_Vessels_OpenTank$tank2_Medium_ThermodynamicState__desc = {
  "Modelica_Fluid_Vessels_OpenTank$tank2_Medium_ThermodynamicState", /* package_record__X */
  "Modelica.Fluid.Vessels.OpenTank$tank2.Medium.ThermodynamicState", /* package.record_X */
  Modelica_Fluid_Vessels_OpenTank$tank2_Medium_ThermodynamicState__desc__fields
};

#define Modelica_Fluid_Vessels_OpenTank$tank2_HeatTransfer$tank2$heatTransfer_Medium_ThermodynamicState__desc_added 1
const char* Modelica_Fluid_Vessels_OpenTank$tank2_HeatTransfer$tank2$heatTransfer_Medium_ThermodynamicState__desc__fields[2] = {"_T","_p"};
struct record_description Modelica_Fluid_Vessels_OpenTank$tank2_HeatTransfer$tank2$heatTransfer_Medium_ThermodynamicState__desc = {
  "Modelica_Fluid_Vessels_OpenTank$tank2_HeatTransfer$tank2$heatTransfer_Medium_ThermodynamicState", /* package_record__X */
  "Modelica.Fluid.Vessels.OpenTank$tank2.HeatTransfer$tank2$heatTransfer.Medium.ThermodynamicState", /* package.record_X */
  Modelica_Fluid_Vessels_OpenTank$tank2_HeatTransfer$tank2$heatTransfer_Medium_ThermodynamicState__desc__fields
};

#ifdef __cplusplus
}
#endif

