/* Jacobians */
/* Simulation code for PipesValveDiscrete generated by the OpenModelica Compiler OpenModelica 1.9.3. */

#include "openmodelica.h"
#include "openmodelica_func.h"
#include "simulation_data.h"
#include "simulation/simulation_info_xml.h"
#include "simulation/simulation_runtime.h"
#include "util/omc_error.h"
#include "simulation/solver/model_help.h"
#include "simulation/solver/delay.h"
#include "simulation/solver/linearSystem.h"
#include "simulation/solver/nonlinearSystem.h"
#include "simulation/solver/mixedSystem.h"

#include <assert.h>
#include <string.h>

#include "PipesValveDiscrete_functions.h"
#include "PipesValveDiscrete_model.h"
#include "PipesValveDiscrete_literals.h"




#if defined(HPCOM) && !defined(_OPENMP)
  #error "HPCOM requires OpenMP or the results are wrong"
#endif
#if defined(_OPENMP)
  #include <omp.h>
#else
  /* dummy omp defines */
  #define omp_get_max_threads() 1
#endif
#include "PipesValveDiscrete_12jac.h"
int PipesValveDiscrete_initialAnalyticJacobianD(void* inData, threadData_t *threadData)
{
  TRACE_PUSH
  TRACE_POP
  return 1;
}
int PipesValveDiscrete_initialAnalyticJacobianC(void* inData, threadData_t *threadData)
{
  TRACE_PUSH
  TRACE_POP
  return 1;
}
int PipesValveDiscrete_initialAnalyticJacobianB(void* inData, threadData_t *threadData)
{
  TRACE_PUSH
  TRACE_POP
  return 1;
}

int PipesValveDiscrete_initialAnalyticJacobianA(void* inData, threadData_t *threadData)
{
  TRACE_PUSH
  DATA* data = ((DATA*)inData);
  int index = PipesValveDiscrete_INDEX_JAC_A;
  
  int i;
  
  data->simulationInfo.analyticJacobians[index].sizeCols = 4;
  data->simulationInfo.analyticJacobians[index].sizeRows = 4;
  data->simulationInfo.analyticJacobians[index].sizeTmpVars = 0;
  data->simulationInfo.analyticJacobians[index].seedVars = (modelica_real*) calloc(4,sizeof(modelica_real));
  data->simulationInfo.analyticJacobians[index].resultVars = (modelica_real*) calloc(4,sizeof(modelica_real));
  data->simulationInfo.analyticJacobians[index].tmpVars = (modelica_real*) calloc(0,sizeof(modelica_real));
  data->simulationInfo.analyticJacobians[index].sparsePattern.leadindex = (unsigned int*) malloc(4*sizeof(int));
  data->simulationInfo.analyticJacobians[index].sparsePattern.index = (unsigned int*) malloc(16*sizeof(int));
  data->simulationInfo.analyticJacobians[index].sparsePattern.numberOfNoneZeros = 16;
  data->simulationInfo.analyticJacobians[index].sparsePattern.colorCols = (unsigned int*) malloc(4*sizeof(int));
  data->simulationInfo.analyticJacobians[index].sparsePattern.maxColors = 4;
  data->simulationInfo.analyticJacobians[index].jacobian = NULL;
  
  /* write lead index of compressed sparse column*/
  const int tmp[4] = {4,4,4,4};
  memcpy(data->simulationInfo.analyticJacobians[index].sparsePattern.leadindex, tmp, 4*sizeof(int));
  
  for(i=1;i<4;++i)
      data->simulationInfo.analyticJacobians[index].sparsePattern.leadindex[i] += data->simulationInfo.analyticJacobians[index].sparsePattern.leadindex[i-1];
  
  /* call sparse index */
  const int tmpElem[16] = {0,1,2,3,0,1,2,3,0,1,2,3,0,1,2,3};
  memcpy(data->simulationInfo.analyticJacobians[index].sparsePattern.index, tmpElem, 16*sizeof(int));
  
  /* write color array */
  data->simulationInfo.analyticJacobians[index].sparsePattern.colorCols[2] = 1;
  data->simulationInfo.analyticJacobians[index].sparsePattern.colorCols[3] = 2;
  data->simulationInfo.analyticJacobians[index].sparsePattern.colorCols[0] = 3;
  data->simulationInfo.analyticJacobians[index].sparsePattern.colorCols[1] = 4;
  TRACE_POP
  return 0;
}

int PipesValveDiscrete_functionJacD_column(void* data, threadData_t *threadData)
{
  TRACE_PUSH
  TRACE_POP
  return 0;
}
int PipesValveDiscrete_functionJacC_column(void* data, threadData_t *threadData)
{
  TRACE_PUSH
  TRACE_POP
  return 0;
}
int PipesValveDiscrete_functionJacB_column(void* data, threadData_t *threadData)
{
  TRACE_PUSH
  TRACE_POP
  return 0;
}
int PipesValveDiscrete_functionJacA_column(void* inData, threadData_t *threadData)
{
  TRACE_PUSH

  DATA* data = ((DATA*)inData);
  int index = PipesValveDiscrete_INDEX_JAC_A;
  
  TRACE_POP
  return 0;
}


