/* Initialization */
/* Simulation code for PipesValveDiscrete generated by the OpenModelica Compiler OpenModelica 1.9.3. */

#include "openmodelica.h"
#include "openmodelica_func.h"
#include "simulation_data.h"
#include "simulation/simulation_info_xml.h"
#include "simulation/simulation_runtime.h"
#include "util/omc_error.h"
#include "simulation/solver/model_help.h"
#include "simulation/solver/delay.h"
#include "simulation/solver/linearSystem.h"
#include "simulation/solver/nonlinearSystem.h"
#include "simulation/solver/mixedSystem.h"

#include <assert.h>
#include <string.h>

#include "PipesValveDiscrete_functions.h"
#include "PipesValveDiscrete_model.h"
#include "PipesValveDiscrete_literals.h"




#if defined(HPCOM) && !defined(_OPENMP)
  #error "HPCOM requires OpenMP or the results are wrong"
#endif
#if defined(_OPENMP)
  #include <omp.h>
#else
  /* dummy omp defines */
  #define omp_get_max_threads() 1
#endif
#include "PipesValveDiscrete_11mix.h"
#include "PipesValveDiscrete_12jac.h"
#if defined(__cplusplus)
extern "C" {
#endif


/*
 equation index: 1
 type: SIMPLE_ASSIGN
 tank1._medium._R = 0.0
 */
void PipesValveDiscrete_eqFunction_1(DATA *data, threadData_t *threadData)
{
  TRACE_PUSH
  const int equationIndexes[2] = {1,1};
  $Ptank1$Pmedium$PR = 0.0;
  TRACE_POP
}
/*
 equation index: 2
 type: SIMPLE_ASSIGN
 tank1._medium._MM = 0.018015268
 */
void PipesValveDiscrete_eqFunction_2(DATA *data, threadData_t *threadData)
{
  TRACE_PUSH
  const int equationIndexes[2] = {1,2};
  $Ptank1$Pmedium$PMM = 0.018015268;
  TRACE_POP
}
/*
 equation index: 3
 type: SIMPLE_ASSIGN
 tank2._medium._R = 0.0
 */
void PipesValveDiscrete_eqFunction_3(DATA *data, threadData_t *threadData)
{
  TRACE_PUSH
  const int equationIndexes[2] = {1,3};
  $Ptank2$Pmedium$PR = 0.0;
  TRACE_POP
}
/*
 equation index: 4
 type: SIMPLE_ASSIGN
 tank2._medium._MM = 0.018015268
 */
void PipesValveDiscrete_eqFunction_4(DATA *data, threadData_t *threadData)
{
  TRACE_PUSH
  const int equationIndexes[2] = {1,4};
  $Ptank2$Pmedium$PMM = 0.018015268;
  TRACE_POP
}
/*
 equation index: 5
 type: SIMPLE_ASSIGN
 tank1._medium._d = 995.586
 */
void PipesValveDiscrete_eqFunction_5(DATA *data, threadData_t *threadData)
{
  TRACE_PUSH
  const int equationIndexes[2] = {1,5};
  $Ptank1$Pmedium$Pd = 995.586;
  TRACE_POP
}
/*
 equation index: 6
 type: SIMPLE_ASSIGN
 tank1._medium._X[1] = 1.0
 */
void PipesValveDiscrete_eqFunction_6(DATA *data, threadData_t *threadData)
{
  TRACE_PUSH
  const int equationIndexes[2] = {1,6};
  $Ptank1$Pmedium$PX$lB1$rB = 1.0;
  TRACE_POP
}
/*
 equation index: 7
 type: SIMPLE_ASSIGN
 tank1._Wb_flow = 0.0
 */
void PipesValveDiscrete_eqFunction_7(DATA *data, threadData_t *threadData)
{
  TRACE_PUSH
  const int equationIndexes[2] = {1,7};
  $Ptank1$PWb_flow = 0.0;
  TRACE_POP
}
/*
 equation index: 8
 type: SIMPLE_ASSIGN
 pipe._flowModel._Ib_flows[1] = 0.0
 */
void PipesValveDiscrete_eqFunction_8(DATA *data, threadData_t *threadData)
{
  TRACE_PUSH
  const int equationIndexes[2] = {1,8};
  $Ppipe$PflowModel$PIb_flows$lB1$rB = 0.0;
  TRACE_POP
}
/*
 equation index: 9
 type: SIMPLE_ASSIGN
 tank2._medium._d = 995.586
 */
void PipesValveDiscrete_eqFunction_9(DATA *data, threadData_t *threadData)
{
  TRACE_PUSH
  const int equationIndexes[2] = {1,9};
  $Ptank2$Pmedium$Pd = 995.586;
  TRACE_POP
}
/*
 equation index: 10
 type: SIMPLE_ASSIGN
 tank2._medium._X[1] = 1.0
 */
void PipesValveDiscrete_eqFunction_10(DATA *data, threadData_t *threadData)
{
  TRACE_PUSH
  const int equationIndexes[2] = {1,10};
  $Ptank2$Pmedium$PX$lB1$rB = 1.0;
  TRACE_POP
}
/*
 equation index: 11
 type: SIMPLE_ASSIGN
 tank2._Wb_flow = 0.0
 */
void PipesValveDiscrete_eqFunction_11(DATA *data, threadData_t *threadData)
{
  TRACE_PUSH
  const int equationIndexes[2] = {1,11};
  $Ptank2$PWb_flow = 0.0;
  TRACE_POP
}
/*
 equation index: 12
 type: SIMPLE_ASSIGN
 tank1._heatTransfer._heatPorts[1]._Q_flow = 0.0
 */
void PipesValveDiscrete_eqFunction_12(DATA *data, threadData_t *threadData)
{
  TRACE_PUSH
  const int equationIndexes[2] = {1,12};
  $Ptank1$PheatTransfer$PheatPorts$lB1$rB$PQ_flow = 0.0;
  TRACE_POP
}
/*
 equation index: 13
 type: SIMPLE_ASSIGN
 tank2._heatTransfer._heatPorts[1]._Q_flow = 0.0
 */
void PipesValveDiscrete_eqFunction_13(DATA *data, threadData_t *threadData)
{
  TRACE_PUSH
  const int equationIndexes[2] = {1,13};
  $Ptank2$PheatTransfer$PheatPorts$lB1$rB$PQ_flow = 0.0;
  TRACE_POP
}
/*
 equation index: 14
 type: SIMPLE_ASSIGN
 tank1._m_flow_nominal = 100.0 * system.m_flow_small
 */
void PipesValveDiscrete_eqFunction_14(DATA *data, threadData_t *threadData)
{
  TRACE_PUSH
  const int equationIndexes[2] = {1,14};
  $Ptank1$Pm_flow_nominal = (100.0 * $Psystem$Pm_flow_small);
  TRACE_POP
}
/*
 equation index: 15
 type: SIMPLE_ASSIGN
 tank1._T_ambient = system.T_ambient
 */
void PipesValveDiscrete_eqFunction_15(DATA *data, threadData_t *threadData)
{
  TRACE_PUSH
  const int equationIndexes[2] = {1,15};
  $Ptank1$PT_ambient = $Psystem$PT_ambient;
  TRACE_POP
}
/*
 equation index: 16
 type: SIMPLE_ASSIGN
 tank1._heatTransfer._use_k = tank1.use_HeatTransfer
 */
void PipesValveDiscrete_eqFunction_16(DATA *data, threadData_t *threadData)
{
  TRACE_PUSH
  const int equationIndexes[2] = {1,16};
  $Ptank1$PheatTransfer$Puse_k = $Ptank1$Puse_HeatTransfer;
  TRACE_POP
}
/*
 equation index: 17
 type: SIMPLE_ASSIGN
 tank1._heatTransfer._T_ambient = system.T_ambient
 */
void PipesValveDiscrete_eqFunction_17(DATA *data, threadData_t *threadData)
{
  TRACE_PUSH
  const int equationIndexes[2] = {1,17};
  $Ptank1$PheatTransfer$PT_ambient = $Psystem$PT_ambient;
  TRACE_POP
}
/*
 equation index: 18
 type: SIMPLE_ASSIGN
 tank2._m_flow_nominal = 100.0 * system.m_flow_small
 */
void PipesValveDiscrete_eqFunction_18(DATA *data, threadData_t *threadData)
{
  TRACE_PUSH
  const int equationIndexes[2] = {1,18};
  $Ptank2$Pm_flow_nominal = (100.0 * $Psystem$Pm_flow_small);
  TRACE_POP
}
/*
 equation index: 19
 type: SIMPLE_ASSIGN
 tank2._T_ambient = system.T_ambient
 */
void PipesValveDiscrete_eqFunction_19(DATA *data, threadData_t *threadData)
{
  TRACE_PUSH
  const int equationIndexes[2] = {1,19};
  $Ptank2$PT_ambient = $Psystem$PT_ambient;
  TRACE_POP
}
/*
 equation index: 20
 type: SIMPLE_ASSIGN
 tank2._heatTransfer._use_k = tank2.use_HeatTransfer
 */
void PipesValveDiscrete_eqFunction_20(DATA *data, threadData_t *threadData)
{
  TRACE_PUSH
  const int equationIndexes[2] = {1,20};
  $Ptank2$PheatTransfer$Puse_k = $Ptank2$Puse_HeatTransfer;
  TRACE_POP
}
/*
 equation index: 21
 type: SIMPLE_ASSIGN
 tank2._heatTransfer._T_ambient = system.T_ambient
 */
void PipesValveDiscrete_eqFunction_21(DATA *data, threadData_t *threadData)
{
  TRACE_PUSH
  const int equationIndexes[2] = {1,21};
  $Ptank2$PheatTransfer$PT_ambient = $Psystem$PT_ambient;
  TRACE_POP
}
/*
 equation index: 22
 type: SIMPLE_ASSIGN
 valve._m_flow_start = system.m_flow_start
 */
void PipesValveDiscrete_eqFunction_22(DATA *data, threadData_t *threadData)
{
  TRACE_PUSH
  const int equationIndexes[2] = {1,22};
  $Pvalve$Pm_flow_start = $Psystem$Pm_flow_start;
  TRACE_POP
}
/*
 equation index: 23
 type: SIMPLE_ASSIGN
 system._p_start = system.p_ambient
 */
void PipesValveDiscrete_eqFunction_23(DATA *data, threadData_t *threadData)
{
  TRACE_PUSH
  const int equationIndexes[2] = {1,23};
  $Psystem$Pp_start = $Psystem$Pp_ambient;
  TRACE_POP
}
/*
 equation index: 24
 type: SIMPLE_ASSIGN
 valve._dp_start = 0.01 * system.p_start
 */
void PipesValveDiscrete_eqFunction_24(DATA *data, threadData_t *threadData)
{
  TRACE_PUSH
  const int equationIndexes[2] = {1,24};
  $Pvalve$Pdp_start = (0.01 * $Psystem$Pp_start);
  TRACE_POP
}
/*
 equation index: 25
 type: SIMPLE_ASSIGN
 pipe._p_a_start = system.p_start
 */
void PipesValveDiscrete_eqFunction_25(DATA *data, threadData_t *threadData)
{
  TRACE_PUSH
  const int equationIndexes[2] = {1,25};
  $Ppipe$Pp_a_start = $Psystem$Pp_start;
  TRACE_POP
}
/*
 equation index: 26
 type: SIMPLE_ASSIGN
 pipe._p_b_start = pipe.p_a_start
 */
void PipesValveDiscrete_eqFunction_26(DATA *data, threadData_t *threadData)
{
  TRACE_PUSH
  const int equationIndexes[2] = {1,26};
  $Ppipe$Pp_b_start = $Ppipe$Pp_a_start;
  TRACE_POP
}
/*
 equation index: 27
 type: SIMPLE_ASSIGN
 pipe._flowModel._p_b_start = pipe.p_b_start
 */
void PipesValveDiscrete_eqFunction_27(DATA *data, threadData_t *threadData)
{
  TRACE_PUSH
  const int equationIndexes[2] = {1,27};
  $Ppipe$PflowModel$Pp_b_start = $Ppipe$Pp_b_start;
  TRACE_POP
}
/*
 equation index: 28
 type: SIMPLE_ASSIGN
 pipe._flowModel._p_a_start = pipe.p_a_start
 */
void PipesValveDiscrete_eqFunction_28(DATA *data, threadData_t *threadData)
{
  TRACE_PUSH
  const int equationIndexes[2] = {1,28};
  $Ppipe$PflowModel$Pp_a_start = $Ppipe$Pp_a_start;
  TRACE_POP
}
/*
 equation index: 29
 type: SIMPLE_ASSIGN
 tank2._medium._T = $_start(tank2.medium.T)
 */
void PipesValveDiscrete_eqFunction_29(DATA *data, threadData_t *threadData)
{
  TRACE_PUSH
  const int equationIndexes[2] = {1,29};
  $Ptank2$Pmedium$PT = $P$ATTRIBUTE$Ptank2$Pmedium$PT.start;
  TRACE_POP
}
/*
 equation index: 30
 type: SIMPLE_ASSIGN
 tank2._level = $_start(tank2.level)
 */
void PipesValveDiscrete_eqFunction_30(DATA *data, threadData_t *threadData)
{
  TRACE_PUSH
  const int equationIndexes[2] = {1,30};
  $Ptank2$Plevel = $P$ATTRIBUTE$Ptank2$Plevel.start;
  TRACE_POP
}
/*
 equation index: 31
 type: SIMPLE_ASSIGN
 tank1._level = $_start(tank1.level)
 */
void PipesValveDiscrete_eqFunction_31(DATA *data, threadData_t *threadData)
{
  TRACE_PUSH
  const int equationIndexes[2] = {1,31};
  $Ptank1$Plevel = $P$ATTRIBUTE$Ptank1$Plevel.start;
  TRACE_POP
}
/*
 equation index: 32
 type: SIMPLE_ASSIGN
 tank1._medium._T = $_start(tank1.medium.T)
 */
void PipesValveDiscrete_eqFunction_32(DATA *data, threadData_t *threadData)
{
  TRACE_PUSH
  const int equationIndexes[2] = {1,32};
  $Ptank1$Pmedium$PT = $P$ATTRIBUTE$Ptank1$Pmedium$PT.start;
  TRACE_POP
}
/*
 equation index: 33
 type: SIMPLE_ASSIGN
 system._T_start = system.T_ambient
 */
void PipesValveDiscrete_eqFunction_33(DATA *data, threadData_t *threadData)
{
  TRACE_PUSH
  const int equationIndexes[2] = {1,33};
  $Psystem$PT_start = $Psystem$PT_ambient;
  TRACE_POP
}
/*
 equation index: 34
 type: SIMPLE_ASSIGN
 valve._k = DIVISION(valve.m_flow_nominal, valve.dp_nominal)
 */
void PipesValveDiscrete_eqFunction_34(DATA *data, threadData_t *threadData)
{
  TRACE_PUSH
  const int equationIndexes[2] = {1,34};
  $Pvalve$Pk = DIVISION_SIM($Pvalve$Pm_flow_nominal,$Pvalve$Pdp_nominal,"valve.dp_nominal",equationIndexes);
  TRACE_POP
}
/*
 equation index: 35
 type: SIMPLE_ASSIGN
 valve._m_flow_small = system.m_flow_small
 */
void PipesValveDiscrete_eqFunction_35(DATA *data, threadData_t *threadData)
{
  TRACE_PUSH
  const int equationIndexes[2] = {1,35};
  $Pvalve$Pm_flow_small = $Psystem$Pm_flow_small;
  TRACE_POP
}
/*
 equation index: 36
 type: SIMPLE_ASSIGN
 tank2._T_start = system.T_start
 */
void PipesValveDiscrete_eqFunction_36(DATA *data, threadData_t *threadData)
{
  TRACE_PUSH
  const int equationIndexes[2] = {1,36};
  $Ptank2$PT_start = $Psystem$PT_start;
  TRACE_POP
}
/*
 equation index: 37
 type: SIMPLE_ASSIGN
 tank2._p_ambient = system.p_ambient
 */
void PipesValveDiscrete_eqFunction_37(DATA *data, threadData_t *threadData)
{
  TRACE_PUSH
  const int equationIndexes[2] = {1,37};
  $Ptank2$Pp_ambient = $Psystem$Pp_ambient;
  TRACE_POP
}
/*
 equation index: 38
 type: SIMPLE_ASSIGN
 tank2._p_start = tank2.p_ambient
 */
void PipesValveDiscrete_eqFunction_38(DATA *data, threadData_t *threadData)
{
  TRACE_PUSH
  const int equationIndexes[2] = {1,38};
  $Ptank2$Pp_start = $Ptank2$Pp_ambient;
  TRACE_POP
}
/*
 equation index: 39
 type: SIMPLE_ASSIGN
 tank2._h_start = Modelica.Fluid.Vessels.OpenTank$tank2.Medium.specificEnthalpy_pTX(tank2.p_start, tank2.T_start, {tank2.X_start[1]})
 */
void PipesValveDiscrete_eqFunction_39(DATA *data, threadData_t *threadData)
{
  TRACE_PUSH
  const int equationIndexes[2] = {1,39};
  real_array tmp0;
  array_alloc_scalar_real_array(&tmp0, 1, (modelica_real)$Ptank2$PX_start$lB1$rB);
  $Ptank2$Ph_start = omc_Modelica_Fluid_Vessels_OpenTank$tank2_Medium_specificEnthalpy__pTX(threadData, $Ptank2$Pp_start, $Ptank2$PT_start, tmp0);
  TRACE_POP
}
/*
 equation index: 40
 type: SIMPLE_ASSIGN
 tank2._m_flow_small = system.m_flow_small
 */
void PipesValveDiscrete_eqFunction_40(DATA *data, threadData_t *threadData)
{
  TRACE_PUSH
  const int equationIndexes[2] = {1,40};
  $Ptank2$Pm_flow_small = $Psystem$Pm_flow_small;
  TRACE_POP
}
/*
 equation index: 41
 type: SIMPLE_ASSIGN
 pipe._flowModel._m_flow_small = system.m_flow_small
 */
void PipesValveDiscrete_eqFunction_41(DATA *data, threadData_t *threadData)
{
  TRACE_PUSH
  const int equationIndexes[2] = {1,41};
  $Ppipe$PflowModel$Pm_flow_small = $Psystem$Pm_flow_small;
  TRACE_POP
}
/*
 equation index: 42
 type: SIMPLE_ASSIGN
 pipe._flowModel._m_flow_nominal = 100.0 * pipe.flowModel.m_flow_small
 */
void PipesValveDiscrete_eqFunction_42(DATA *data, threadData_t *threadData)
{
  TRACE_PUSH
  const int equationIndexes[2] = {1,42};
  $Ppipe$PflowModel$Pm_flow_nominal = (100.0 * $Ppipe$PflowModel$Pm_flow_small);
  TRACE_POP
}
/*
 equation index: 43
 type: SIMPLE_ASSIGN
 pipe._flowModel._g = system.g
 */
void PipesValveDiscrete_eqFunction_43(DATA *data, threadData_t *threadData)
{
  TRACE_PUSH
  const int equationIndexes[2] = {1,43};
  $Ppipe$PflowModel$Pg = $Psystem$Pg;
  TRACE_POP
}
/*
 equation index: 44
 type: SIMPLE_ASSIGN
 pipe._flowModel._nParallel = pipe.nParallel
 */
void PipesValveDiscrete_eqFunction_44(DATA *data, threadData_t *threadData)
{
  TRACE_PUSH
  const int equationIndexes[2] = {1,44};
  $Ppipe$PflowModel$PnParallel = $Ppipe$PnParallel;
  TRACE_POP
}
/*
 equation index: 45
 type: SIMPLE_ASSIGN
 pipe._perimeter = 3.141592653589793 * pipe.diameter
 */
void PipesValveDiscrete_eqFunction_45(DATA *data, threadData_t *threadData)
{
  TRACE_PUSH
  const int equationIndexes[2] = {1,45};
  $Ppipe$Pperimeter = (3.141592653589793 * $Ppipe$Pdiameter);
  TRACE_POP
}
/*
 equation index: 46
 type: SIMPLE_ASSIGN
 pipe._crossArea = 0.7853981633974483 * pipe.diameter ^ 2.0
 */
void PipesValveDiscrete_eqFunction_46(DATA *data, threadData_t *threadData)
{
  TRACE_PUSH
  const int equationIndexes[2] = {1,46};
  modelica_real tmp1;
  tmp1 = $Ppipe$Pdiameter;
  $Ppipe$PcrossArea = (0.7853981633974483 * (tmp1 * tmp1));
  TRACE_POP
}
/*
 equation index: 47
 type: SIMPLE_ASSIGN
 tank1._T_start = system.T_start
 */
void PipesValveDiscrete_eqFunction_47(DATA *data, threadData_t *threadData)
{
  TRACE_PUSH
  const int equationIndexes[2] = {1,47};
  $Ptank1$PT_start = $Psystem$PT_start;
  TRACE_POP
}
/*
 equation index: 48
 type: SIMPLE_ASSIGN
 tank1._p_ambient = system.p_ambient
 */
void PipesValveDiscrete_eqFunction_48(DATA *data, threadData_t *threadData)
{
  TRACE_PUSH
  const int equationIndexes[2] = {1,48};
  $Ptank1$Pp_ambient = $Psystem$Pp_ambient;
  TRACE_POP
}
/*
 equation index: 49
 type: SIMPLE_ASSIGN
 tank1._p_start = tank1.p_ambient
 */
void PipesValveDiscrete_eqFunction_49(DATA *data, threadData_t *threadData)
{
  TRACE_PUSH
  const int equationIndexes[2] = {1,49};
  $Ptank1$Pp_start = $Ptank1$Pp_ambient;
  TRACE_POP
}
/*
 equation index: 50
 type: SIMPLE_ASSIGN
 tank1._h_start = Modelica.Fluid.Vessels.OpenTank$tank1.Medium.specificEnthalpy_pTX(tank1.p_start, tank1.T_start, {tank1.X_start[1]})
 */
void PipesValveDiscrete_eqFunction_50(DATA *data, threadData_t *threadData)
{
  TRACE_PUSH
  const int equationIndexes[2] = {1,50};
  real_array tmp2;
  array_alloc_scalar_real_array(&tmp2, 1, (modelica_real)$Ptank1$PX_start$lB1$rB);
  $Ptank1$Ph_start = omc_Modelica_Fluid_Vessels_OpenTank$tank1_Medium_specificEnthalpy__pTX(threadData, $Ptank1$Pp_start, $Ptank1$PT_start, tmp2);
  TRACE_POP
}
/*
 equation index: 51
 type: SIMPLE_ASSIGN
 tank1._m_flow_small = system.m_flow_small
 */
void PipesValveDiscrete_eqFunction_51(DATA *data, threadData_t *threadData)
{
  TRACE_PUSH
  const int equationIndexes[2] = {1,51};
  $Ptank1$Pm_flow_small = $Psystem$Pm_flow_small;
  TRACE_POP
}
/*
 equation index: 52
 type: SIMPLE_ASSIGN
 pipe._flowModel._dimensions[2] = 4.0 * DIVISION(pipe.crossArea, pipe.perimeter)
 */
void PipesValveDiscrete_eqFunction_52(DATA *data, threadData_t *threadData)
{
  TRACE_PUSH
  const int equationIndexes[2] = {1,52};
  $Ppipe$PflowModel$Pdimensions$lB2$rB = (4.0 * DIVISION_SIM($Ppipe$PcrossArea,$Ppipe$Pperimeter,"pipe.perimeter",equationIndexes));
  TRACE_POP
}
/*
 equation index: 53
 type: SIMPLE_ASSIGN
 pipe._flowModel._dimensions[1] = 4.0 * DIVISION(pipe.crossArea, pipe.perimeter)
 */
void PipesValveDiscrete_eqFunction_53(DATA *data, threadData_t *threadData)
{
  TRACE_PUSH
  const int equationIndexes[2] = {1,53};
  $Ppipe$PflowModel$Pdimensions$lB1$rB = (4.0 * DIVISION_SIM($Ppipe$PcrossArea,$Ppipe$Pperimeter,"pipe.perimeter",equationIndexes));
  TRACE_POP
}
/*
 equation index: 54
 type: SIMPLE_ASSIGN
 tank1._medium._p_bar = 1e-05 * tank1.p_ambient
 */
void PipesValveDiscrete_eqFunction_54(DATA *data, threadData_t *threadData)
{
  TRACE_PUSH
  const int equationIndexes[2] = {1,54};
  $Ptank1$Pmedium$Pp_bar = (1e-05 * $Ptank1$Pp_ambient);
  TRACE_POP
}
/*
 equation index: 55
 type: SIMPLE_ASSIGN
 tank2._medium._p_bar = 1e-05 * tank2.p_ambient
 */
void PipesValveDiscrete_eqFunction_55(DATA *data, threadData_t *threadData)
{
  TRACE_PUSH
  const int equationIndexes[2] = {1,55};
  $Ptank2$Pmedium$Pp_bar = (1e-05 * $Ptank2$Pp_ambient);
  TRACE_POP
}
/*
 equation index: 56
 type: SIMPLE_ASSIGN
 tank1._portAreas[1] = 0.7853981633974483 * tank1.portsData[1].diameter ^ 2.0
 */
void PipesValveDiscrete_eqFunction_56(DATA *data, threadData_t *threadData)
{
  TRACE_PUSH
  const int equationIndexes[2] = {1,56};
  modelica_real tmp3;
  tmp3 = $Ptank1$PportsData$lB1$rB$Pdiameter;
  $Ptank1$PportAreas$lB1$rB = (0.7853981633974483 * (tmp3 * tmp3));
  TRACE_POP
}
/*
 equation index: 57
 type: SIMPLE_ASSIGN
 pipe._flowModel._diameters[1] = 0.5 * (pipe.flowModel.dimensions[1] + pipe.flowModel.dimensions[2])
 */
void PipesValveDiscrete_eqFunction_57(DATA *data, threadData_t *threadData)
{
  TRACE_PUSH
  const int equationIndexes[2] = {1,57};
  $Ppipe$PflowModel$Pdiameters$lB1$rB = (0.5 * ($Ppipe$PflowModel$Pdimensions$lB1$rB + $Ppipe$PflowModel$Pdimensions$lB2$rB));
  TRACE_POP
}
/*
 equation index: 58
 type: SIMPLE_ASSIGN
 tank2._portAreas[1] = 0.7853981633974483 * tank2.portsData[1].diameter ^ 2.0
 */
void PipesValveDiscrete_eqFunction_58(DATA *data, threadData_t *threadData)
{
  TRACE_PUSH
  const int equationIndexes[2] = {1,58};
  modelica_real tmp4;
  tmp4 = $Ptank2$PportsData$lB1$rB$Pdiameter;
  $Ptank2$PportAreas$lB1$rB = (0.7853981633974483 * (tmp4 * tmp4));
  TRACE_POP
}
/*
 equation index: 59
 type: SIMPLE_ASSIGN
 pipe._flowModel._dp_fric_nominal = Modelica.Fluid.Pipes.StaticPipe$pipe.FlowModel$pipe$flowModel.WallFriction.pressureLoss_m_flow(DIVISION(pipe.flowModel.m_flow_nominal, pipe.flowModel.nParallel), 995.586, 995.586, 0.001, 0.001, pipe.length, pipe.flowModel.diameters[1], pipe.crossArea, pipe.roughness, DIVISION(pipe.flowModel.m_flow_small, pipe.flowModel.nParallel), pipe.flowModel.Re_turbulent)
 */
void PipesValveDiscrete_eqFunction_59(DATA *data, threadData_t *threadData)
{
  TRACE_PUSH
  const int equationIndexes[2] = {1,59};
  $Ppipe$PflowModel$Pdp_fric_nominal = omc_Modelica_Fluid_Pipes_StaticPipe$pipe_FlowModel$pipe$flowModel_WallFriction_pressureLoss__m__flow(threadData, DIVISION_SIM($Ppipe$PflowModel$Pm_flow_nominal,$Ppipe$PflowModel$PnParallel,"pipe.flowModel.nParallel",equationIndexes), 995.586, 995.586, 0.001, 0.001, $Ppipe$Plength, $Ppipe$PflowModel$Pdiameters$lB1$rB, $Ppipe$PcrossArea, $Ppipe$Proughness, DIVISION_SIM($Ppipe$PflowModel$Pm_flow_small,$Ppipe$PflowModel$PnParallel,"pipe.flowModel.nParallel",equationIndexes), $Ppipe$PflowModel$PRe_turbulent);
  TRACE_POP
}
/*
 equation index: 60
 type: SIMPLE_ASSIGN
 tank2._fluidVolume = tank2.crossArea * tank2.level
 */
void PipesValveDiscrete_eqFunction_60(DATA *data, threadData_t *threadData)
{
  TRACE_PUSH
  const int equationIndexes[2] = {1,60};
  $Ptank2$PfluidVolume = ($Ptank2$PcrossArea * $Ptank2$Plevel);
  TRACE_POP
}
/*
 equation index: 61
 type: SIMPLE_ASSIGN
 tank2._m = 995.586 * tank2.fluidVolume
 */
void PipesValveDiscrete_eqFunction_61(DATA *data, threadData_t *threadData)
{
  TRACE_PUSH
  const int equationIndexes[2] = {1,61};
  $Ptank2$Pm = (995.586 * $Ptank2$PfluidVolume);
  TRACE_POP
}
/*
 equation index: 62
 type: SIMPLE_ASSIGN
 tank1._fluidVolume = tank1.crossArea * tank1.level
 */
void PipesValveDiscrete_eqFunction_62(DATA *data, threadData_t *threadData)
{
  TRACE_PUSH
  const int equationIndexes[2] = {1,62};
  $Ptank1$PfluidVolume = ($Ptank1$PcrossArea * $Ptank1$Plevel);
  TRACE_POP
}
/*
 equation index: 63
 type: SIMPLE_ASSIGN
 tank1._m = 995.586 * tank1.fluidVolume
 */
void PipesValveDiscrete_eqFunction_63(DATA *data, threadData_t *threadData)
{
  TRACE_PUSH
  const int equationIndexes[2] = {1,63};
  $Ptank1$Pm = (995.586 * $Ptank1$PfluidVolume);
  TRACE_POP
}
/*
 equation index: 64
 type: SIMPLE_ASSIGN
 tank2._medium._T_degC = -273.15 + tank2.medium.T
 */
void PipesValveDiscrete_eqFunction_64(DATA *data, threadData_t *threadData)
{
  TRACE_PUSH
  const int equationIndexes[2] = {1,64};
  $Ptank2$Pmedium$PT_degC = (-273.15 + $Ptank2$Pmedium$PT);
  TRACE_POP
}
/*
 equation index: 65
 type: SIMPLE_ASSIGN
 tank2._medium._u = 4184.0 * tank2.medium.T_degC
 */
void PipesValveDiscrete_eqFunction_65(DATA *data, threadData_t *threadData)
{
  TRACE_PUSH
  const int equationIndexes[2] = {1,65};
  $Ptank2$Pmedium$Pu = (4184.0 * $Ptank2$Pmedium$PT_degC);
  TRACE_POP
}
/*
 equation index: 66
 type: SIMPLE_ASSIGN
 tank2._U = tank2.m * tank2.medium.u
 */
void PipesValveDiscrete_eqFunction_66(DATA *data, threadData_t *threadData)
{
  TRACE_PUSH
  const int equationIndexes[2] = {1,66};
  $Ptank2$PU = ($Ptank2$Pm * $Ptank2$Pmedium$Pu);
  TRACE_POP
}
/*
 equation index: 67
 type: SIMPLE_ASSIGN
 tank1._medium._T_degC = -273.15 + tank1.medium.T
 */
void PipesValveDiscrete_eqFunction_67(DATA *data, threadData_t *threadData)
{
  TRACE_PUSH
  const int equationIndexes[2] = {1,67};
  $Ptank1$Pmedium$PT_degC = (-273.15 + $Ptank1$Pmedium$PT);
  TRACE_POP
}
/*
 equation index: 68
 type: SIMPLE_ASSIGN
 tank1._medium._u = 4184.0 * tank1.medium.T_degC
 */
void PipesValveDiscrete_eqFunction_68(DATA *data, threadData_t *threadData)
{
  TRACE_PUSH
  const int equationIndexes[2] = {1,68};
  $Ptank1$Pmedium$Pu = (4184.0 * $Ptank1$Pmedium$PT_degC);
  TRACE_POP
}
/*
 equation index: 69
 type: SIMPLE_ASSIGN
 tank1._U = tank1.m * tank1.medium.u
 */
void PipesValveDiscrete_eqFunction_69(DATA *data, threadData_t *threadData)
{
  TRACE_PUSH
  const int equationIndexes[2] = {1,69};
  $Ptank1$PU = ($Ptank1$Pm * $Ptank1$Pmedium$Pu);
  TRACE_POP
}
/*
 equation index: 70
 type: SIMPLE_ASSIGN
 tank1._ports[1]._h_outflow = Modelica.Fluid.Vessels.OpenTank$tank1.Medium.specificEnthalpy_pTX(tank1.p_ambient, tank1.medium.T, {1.0})
 */
void PipesValveDiscrete_eqFunction_70(DATA *data, threadData_t *threadData)
{
  TRACE_PUSH
  const int equationIndexes[2] = {1,70};
  $Ptank1$Pports$lB1$rB$Ph_outflow = omc_Modelica_Fluid_Vessels_OpenTank$tank1_Medium_specificEnthalpy__pTX(threadData, $Ptank1$Pp_ambient, $Ptank1$Pmedium$PT, _OMC_LIT30);
  TRACE_POP
}
/*
 equation index: 71
 type: SIMPLE_ASSIGN
 tank1._heatTransfer._surfaceAreas[1] = tank1.crossArea + 3.544907701811032 * sqrt(tank1.crossArea) * tank1.level
 */
void PipesValveDiscrete_eqFunction_71(DATA *data, threadData_t *threadData)
{
  TRACE_PUSH
  const int equationIndexes[2] = {1,71};
  modelica_real tmp5;
  tmp5 = $Ptank1$PcrossArea; 
  if(!(tmp5 >= 0.0))
  {
      {
        FILE_INFO info = {"",0,0,0,0,0};
        omc_assert_warning(info, "The following assertion has been violated at time %f", data->localData[0]->timeValue);
        throwStreamPrintWithEquationIndexes(threadData, equationIndexes, "Model error: Argument of sqrt(tank1.crossArea) was %g should be >= 0", tmp5);
      }
  }
  $Ptank1$PheatTransfer$PsurfaceAreas$lB1$rB = ($Ptank1$PcrossArea + (3.544907701811032 * (sqrt(tmp5) * $Ptank1$Plevel)));
  TRACE_POP
}
/*
 equation index: 72
 type: SIMPLE_ASSIGN
 tank1._heatTransfer._Ts[1] = Modelica.Fluid.Vessels.OpenTank$tank1.HeatTransfer$tank1$heatTransfer.Medium.temperature(Modelica.Fluid.Vessels.OpenTank$tank1.HeatTransfer$tank1$heatTransfer.Medium.ThermodynamicState(tank1.p_ambient, tank1.medium.T))
 */
void PipesValveDiscrete_eqFunction_72(DATA *data, threadData_t *threadData)
{
  TRACE_PUSH
  const int equationIndexes[2] = {1,72};
  $Ptank1$PheatTransfer$PTs$lB1$rB = omc_Modelica_Fluid_Vessels_OpenTank$tank1_HeatTransfer$tank1$heatTransfer_Medium_temperature(threadData, omc_Modelica_Fluid_Vessels_OpenTank$tank1_HeatTransfer$tank1$heatTransfer_Medium_ThermodynamicState(threadData, $Ptank1$Pp_ambient, $Ptank1$Pmedium$PT));
  TRACE_POP
}
/*
 equation index: 73
 type: SIMPLE_ASSIGN
 tank1._vessel_ps_static[1] = 995.586 * max(0.0, tank1.level - tank1.portsData[1].height) * system.g + tank1.p_ambient
 */
void PipesValveDiscrete_eqFunction_73(DATA *data, threadData_t *threadData)
{
  TRACE_PUSH
  const int equationIndexes[2] = {1,73};
  $Ptank1$Pvessel_ps_static$lB1$rB = ((995.586 * (fmax(0.0,($Ptank1$Plevel - $Ptank1$PportsData$lB1$rB$Pheight)) * $Psystem$Pg)) + $Ptank1$Pp_ambient);
  TRACE_POP
}
/*
 equation index: 74
 type: SIMPLE_ASSIGN
 tank1._ports_penetration[1] = Modelica.Fluid.Utilities.regStep(tank1.level + -0.1 * tank1.portsData[1].diameter - tank1.portsData[1].height, 1.0, 0.001, 0.1 * tank1.portsData[1].diameter)
 */
void PipesValveDiscrete_eqFunction_74(DATA *data, threadData_t *threadData)
{
  TRACE_PUSH
  const int equationIndexes[2] = {1,74};
  $Ptank1$Pports_penetration$lB1$rB = omc_Modelica_Fluid_Utilities_regStep(threadData, ($Ptank1$Plevel + ((-0.1 * $Ptank1$PportsData$lB1$rB$Pdiameter) - $Ptank1$PportsData$lB1$rB$Pheight)), 1.0, 0.001, (0.1 * $Ptank1$PportsData$lB1$rB$Pdiameter));
  TRACE_POP
}
/*
 equation index: 75
 type: SIMPLE_ASSIGN
 tank1._regularFlow[1] = tank1.level >= tank1.portsData[1].height
 */
void PipesValveDiscrete_eqFunction_75(DATA *data, threadData_t *threadData)
{
  TRACE_PUSH
  const int equationIndexes[2] = {1,75};
  modelica_boolean tmp6;
  RELATIONHYSTERESIS(tmp6, $Ptank1$Plevel, $Ptank1$PportsData$lB1$rB$Pheight, 0, GreaterEq);
  $Ptank1$PregularFlow$lB1$rB = tmp6;
  TRACE_POP
}
/*
 equation index: 76
 type: SIMPLE_ASSIGN
 pipe._flowModel._states[1]._T = 273.15 + tank1.ports[1].h_outflow / 4184.0
 */
void PipesValveDiscrete_eqFunction_76(DATA *data, threadData_t *threadData)
{
  TRACE_PUSH
  const int equationIndexes[2] = {1,76};
  modelica_real tmp7;
  tmp7 = 4184.0;
  if (tmp7 == 0) {throwStreamPrint(threadData, "Division by zero %s", "tank1.ports[1].h_outflow / 4184.0");}
  $Ppipe$PflowModel$Pstates$lB1$rB$PT = (273.15 + ($Ptank1$Pports$lB1$rB$Ph_outflow / 4184.0));
  TRACE_POP
}
/*
 equation index: 77
 type: SIMPLE_ASSIGN
 valve._port_b._h_outflow = tank1.ports[1].h_outflow - system.g * pipe.height_ab
 */
void PipesValveDiscrete_eqFunction_77(DATA *data, threadData_t *threadData)
{
  TRACE_PUSH
  const int equationIndexes[2] = {1,77};
  $Pvalve$Pport_b$Ph_outflow = ($Ptank1$Pports$lB1$rB$Ph_outflow - ($Psystem$Pg * $Ppipe$Pheight_ab));
  TRACE_POP
}
/*
 equation index: 78
 type: SIMPLE_ASSIGN
 tank2._ports[1]._h_outflow = Modelica.Fluid.Vessels.OpenTank$tank2.Medium.specificEnthalpy_pTX(tank2.p_ambient, tank2.medium.T, {1.0})
 */
void PipesValveDiscrete_eqFunction_78(DATA *data, threadData_t *threadData)
{
  TRACE_PUSH
  const int equationIndexes[2] = {1,78};
  $Ptank2$Pports$lB1$rB$Ph_outflow = omc_Modelica_Fluid_Vessels_OpenTank$tank2_Medium_specificEnthalpy__pTX(threadData, $Ptank2$Pp_ambient, $Ptank2$Pmedium$PT, _OMC_LIT30);
  TRACE_POP
}
/*
 equation index: 79
 type: SIMPLE_ASSIGN
 pipe._port_a._h_outflow = tank2.ports[1].h_outflow + system.g * pipe.height_ab
 */
void PipesValveDiscrete_eqFunction_79(DATA *data, threadData_t *threadData)
{
  TRACE_PUSH
  const int equationIndexes[2] = {1,79};
  $Ppipe$Pport_a$Ph_outflow = ($Ptank2$Pports$lB1$rB$Ph_outflow + ($Psystem$Pg * $Ppipe$Pheight_ab));
  TRACE_POP
}
/*
 equation index: 80
 type: SIMPLE_ASSIGN
 pipe._flowModel._states[2]._T = 273.15 + tank2.ports[1].h_outflow / 4184.0
 */
void PipesValveDiscrete_eqFunction_80(DATA *data, threadData_t *threadData)
{
  TRACE_PUSH
  const int equationIndexes[2] = {1,80};
  modelica_real tmp8;
  tmp8 = 4184.0;
  if (tmp8 == 0) {throwStreamPrint(threadData, "Division by zero %s", "tank2.ports[1].h_outflow / 4184.0");}
  $Ppipe$PflowModel$Pstates$lB2$rB$PT = (273.15 + ($Ptank2$Pports$lB1$rB$Ph_outflow / 4184.0));
  TRACE_POP
}
/*
 equation index: 81
 type: SIMPLE_ASSIGN
 tank2._heatTransfer._surfaceAreas[1] = tank2.crossArea + 3.544907701811032 * sqrt(tank2.crossArea) * tank2.level
 */
void PipesValveDiscrete_eqFunction_81(DATA *data, threadData_t *threadData)
{
  TRACE_PUSH
  const int equationIndexes[2] = {1,81};
  modelica_real tmp9;
  tmp9 = $Ptank2$PcrossArea; 
  if(!(tmp9 >= 0.0))
  {
      {
        FILE_INFO info = {"",0,0,0,0,0};
        omc_assert_warning(info, "The following assertion has been violated at time %f", data->localData[0]->timeValue);
        throwStreamPrintWithEquationIndexes(threadData, equationIndexes, "Model error: Argument of sqrt(tank2.crossArea) was %g should be >= 0", tmp9);
      }
  }
  $Ptank2$PheatTransfer$PsurfaceAreas$lB1$rB = ($Ptank2$PcrossArea + (3.544907701811032 * (sqrt(tmp9) * $Ptank2$Plevel)));
  TRACE_POP
}
/*
 equation index: 82
 type: SIMPLE_ASSIGN
 tank2._heatTransfer._Ts[1] = Modelica.Fluid.Vessels.OpenTank$tank2.HeatTransfer$tank2$heatTransfer.Medium.temperature(Modelica.Fluid.Vessels.OpenTank$tank2.HeatTransfer$tank2$heatTransfer.Medium.ThermodynamicState(tank2.p_ambient, tank2.medium.T))
 */
void PipesValveDiscrete_eqFunction_82(DATA *data, threadData_t *threadData)
{
  TRACE_PUSH
  const int equationIndexes[2] = {1,82};
  $Ptank2$PheatTransfer$PTs$lB1$rB = omc_Modelica_Fluid_Vessels_OpenTank$tank2_HeatTransfer$tank2$heatTransfer_Medium_temperature(threadData, omc_Modelica_Fluid_Vessels_OpenTank$tank2_HeatTransfer$tank2$heatTransfer_Medium_ThermodynamicState(threadData, $Ptank2$Pp_ambient, $Ptank2$Pmedium$PT));
  TRACE_POP
}
/*
 equation index: 83
 type: SIMPLE_ASSIGN
 tank2._vessel_ps_static[1] = 995.586 * max(0.0, tank2.level - tank2.portsData[1].height) * system.g + tank2.p_ambient
 */
void PipesValveDiscrete_eqFunction_83(DATA *data, threadData_t *threadData)
{
  TRACE_PUSH
  const int equationIndexes[2] = {1,83};
  $Ptank2$Pvessel_ps_static$lB1$rB = ((995.586 * (fmax(0.0,($Ptank2$Plevel - $Ptank2$PportsData$lB1$rB$Pheight)) * $Psystem$Pg)) + $Ptank2$Pp_ambient);
  TRACE_POP
}
/*
 equation index: 84
 type: SIMPLE_ASSIGN
 tank2._ports_penetration[1] = Modelica.Fluid.Utilities.regStep(tank2.level + -0.1 * tank2.portsData[1].diameter - tank2.portsData[1].height, 1.0, 0.001, 0.1 * tank2.portsData[1].diameter)
 */
void PipesValveDiscrete_eqFunction_84(DATA *data, threadData_t *threadData)
{
  TRACE_PUSH
  const int equationIndexes[2] = {1,84};
  $Ptank2$Pports_penetration$lB1$rB = omc_Modelica_Fluid_Utilities_regStep(threadData, ($Ptank2$Plevel + ((-0.1 * $Ptank2$PportsData$lB1$rB$Pdiameter) - $Ptank2$PportsData$lB1$rB$Pheight)), 1.0, 0.001, (0.1 * $Ptank2$PportsData$lB1$rB$Pdiameter));
  TRACE_POP
}
/*
 equation index: 85
 type: SIMPLE_ASSIGN
 tank2._regularFlow[1] = tank2.level >= tank2.portsData[1].height
 */
void PipesValveDiscrete_eqFunction_85(DATA *data, threadData_t *threadData)
{
  TRACE_PUSH
  const int equationIndexes[2] = {1,85};
  modelica_boolean tmp10;
  RELATIONHYSTERESIS(tmp10, $Ptank2$Plevel, $Ptank2$PportsData$lB1$rB$Pheight, 1, GreaterEq);
  $Ptank2$PregularFlow$lB1$rB = tmp10;
  TRACE_POP
}
/*
 equation index: 86
 type: SIMPLE_ASSIGN
 valve._state_a._T = 273.15 + valve.port_b.h_outflow / 4184.0
 */
void PipesValveDiscrete_eqFunction_86(DATA *data, threadData_t *threadData)
{
  TRACE_PUSH
  const int equationIndexes[2] = {1,86};
  modelica_real tmp11;
  tmp11 = 4184.0;
  if (tmp11 == 0) {throwStreamPrint(threadData, "Division by zero %s", "valve.port_b.h_outflow / 4184.0");}
  $Pvalve$Pstate_a$PT = (273.15 + ($Pvalve$Pport_b$Ph_outflow / 4184.0));
  TRACE_POP
}
/*
 equation index: 87
 type: SIMPLE_ASSIGN
 valve._state_b._T = 273.15 + tank2.ports[1].h_outflow / 4184.0
 */
void PipesValveDiscrete_eqFunction_87(DATA *data, threadData_t *threadData)
{
  TRACE_PUSH
  const int equationIndexes[2] = {1,87};
  modelica_real tmp12;
  tmp12 = 4184.0;
  if (tmp12 == 0) {throwStreamPrint(threadData, "Division by zero %s", "tank2.ports[1].h_outflow / 4184.0");}
  $Pvalve$Pstate_b$PT = (273.15 + ($Ptank2$Pports$lB1$rB$Ph_outflow / 4184.0));
  TRACE_POP
}
/*
 equation index: 88
 type: SIMPLE_ASSIGN
 valve._open = if time >= valveOpening.startTime then not valveOpening.startValue else valveOpening.startValue
 */
void PipesValveDiscrete_eqFunction_88(DATA *data, threadData_t *threadData)
{
  TRACE_PUSH
  const int equationIndexes[2] = {1,88};
  modelica_boolean tmp13;
  RELATIONHYSTERESIS(tmp13, data->localData[0]->timeValue, $PvalveOpening$PstartTime, 2, GreaterEq);
  $Pvalve$Popen = (tmp13?(!$PvalveOpening$PstartValue):$PvalveOpening$PstartValue);
  TRACE_POP
}
/*
 equation index: 89
 type: SIMPLE_ASSIGN
 pipe._flowModel._dp_small = system.dp_small
 */
void PipesValveDiscrete_eqFunction_89(DATA *data, threadData_t *threadData)
{
  TRACE_PUSH
  const int equationIndexes[2] = {1,89};
  $Ppipe$PflowModel$Pdp_small = $Psystem$Pdp_small;
  TRACE_POP
}
/*
 equation index: 90
 type: SIMPLE_ASSIGN
 pipe._flowModel._dp_nominal = 1000.0 * pipe.flowModel.dp_small
 */
void PipesValveDiscrete_eqFunction_90(DATA *data, threadData_t *threadData)
{
  TRACE_PUSH
  const int equationIndexes[2] = {1,90};
  $Ppipe$PflowModel$Pdp_nominal = (1000.0 * $Ppipe$PflowModel$Pdp_small);
  TRACE_POP
}
void PipesValveDiscrete_eqFunction_91(DATA*,threadData_t*);
void PipesValveDiscrete_eqFunction_92(DATA*,threadData_t*);
void PipesValveDiscrete_eqFunction_93(DATA*,threadData_t*);
void PipesValveDiscrete_eqFunction_94(DATA*,threadData_t*);
void PipesValveDiscrete_eqFunction_95(DATA*,threadData_t*);
void PipesValveDiscrete_eqFunction_96(DATA*,threadData_t*);
void PipesValveDiscrete_eqFunction_97(DATA*,threadData_t*);
void PipesValveDiscrete_eqFunction_98(DATA*,threadData_t*);
void PipesValveDiscrete_eqFunction_99(DATA*,threadData_t*);
void PipesValveDiscrete_eqFunction_105(DATA*,threadData_t*);
void PipesValveDiscrete_eqFunction_104(DATA*,threadData_t*);
void PipesValveDiscrete_eqFunction_103(DATA*,threadData_t*);
void PipesValveDiscrete_eqFunction_102(DATA*,threadData_t*);
void PipesValveDiscrete_eqFunction_101(DATA*,threadData_t*);
void PipesValveDiscrete_eqFunction_100(DATA*,threadData_t*);
/*
 equation index: 106
 indexNonlinear: 0
 type: NONLINEAR
 
 vars: {tank2._s[1], tank1._s[1], tank2._ports[1]._p, pipe._flowModel._states[2]._p, pipe._flowModel._states[1]._p, tank1._mb_flow}
 eqns: {91, 92, 93, 94, 95, 96, 97, 98, 99, 105, 104, 103, 102, 101, 100}
 */
void PipesValveDiscrete_eqFunction_106(DATA *data, threadData_t *threadData)
{
  TRACE_PUSH
  const int equationIndexes[2] = {1,106};
  int retValue;
  if(ACTIVE_STREAM(LOG_DT))
  {
    infoStreamPrint(LOG_DT, 1, "Solving nonlinear system 106 (STRICT TEARING SET if tearing enabled) at time = %18.10e", data->localData[0]->timeValue);
    messageClose(LOG_DT);
  }
  /* extrapolate data */
  data->simulationInfo.nonlinearSystemData[0].nlsx[0] = $Ptank2$Ps$lB1$rB;
  data->simulationInfo.nonlinearSystemData[0].nlsxOld[0] = _$Ptank2$Ps$lB1$rB(1) /*old1*/;
  data->simulationInfo.nonlinearSystemData[0].nlsxExtrapolation[0] = extraPolate(data, _$Ptank2$Ps$lB1$rB(1) /*old1*/, _$Ptank2$Ps$lB1$rB(2) /*old2*/, $P$ATTRIBUTE$Ptank2$Ps$lB1$rB.min, $P$ATTRIBUTE$Ptank2$Ps$lB1$rB.max);
  data->simulationInfo.nonlinearSystemData[0].nlsx[1] = $Ptank1$Ps$lB1$rB;
  data->simulationInfo.nonlinearSystemData[0].nlsxOld[1] = _$Ptank1$Ps$lB1$rB(1) /*old1*/;
  data->simulationInfo.nonlinearSystemData[0].nlsxExtrapolation[1] = extraPolate(data, _$Ptank1$Ps$lB1$rB(1) /*old1*/, _$Ptank1$Ps$lB1$rB(2) /*old2*/, $P$ATTRIBUTE$Ptank1$Ps$lB1$rB.min, $P$ATTRIBUTE$Ptank1$Ps$lB1$rB.max);
  data->simulationInfo.nonlinearSystemData[0].nlsx[2] = $Ptank2$Pports$lB1$rB$Pp;
  data->simulationInfo.nonlinearSystemData[0].nlsxOld[2] = _$Ptank2$Pports$lB1$rB$Pp(1) /*old1*/;
  data->simulationInfo.nonlinearSystemData[0].nlsxExtrapolation[2] = extraPolate(data, _$Ptank2$Pports$lB1$rB$Pp(1) /*old1*/, _$Ptank2$Pports$lB1$rB$Pp(2) /*old2*/, $P$ATTRIBUTE$Ptank2$Pports$lB1$rB$Pp.min, $P$ATTRIBUTE$Ptank2$Pports$lB1$rB$Pp.max);
  data->simulationInfo.nonlinearSystemData[0].nlsx[3] = $Ppipe$PflowModel$Pstates$lB2$rB$Pp;
  data->simulationInfo.nonlinearSystemData[0].nlsxOld[3] = _$Ppipe$PflowModel$Pstates$lB2$rB$Pp(1) /*old1*/;
  data->simulationInfo.nonlinearSystemData[0].nlsxExtrapolation[3] = extraPolate(data, _$Ppipe$PflowModel$Pstates$lB2$rB$Pp(1) /*old1*/, _$Ppipe$PflowModel$Pstates$lB2$rB$Pp(2) /*old2*/, $P$ATTRIBUTE$Ppipe$PflowModel$Pstates$lB2$rB$Pp.min, $P$ATTRIBUTE$Ppipe$PflowModel$Pstates$lB2$rB$Pp.max);
  data->simulationInfo.nonlinearSystemData[0].nlsx[4] = $Ppipe$PflowModel$Pstates$lB1$rB$Pp;
  data->simulationInfo.nonlinearSystemData[0].nlsxOld[4] = _$Ppipe$PflowModel$Pstates$lB1$rB$Pp(1) /*old1*/;
  data->simulationInfo.nonlinearSystemData[0].nlsxExtrapolation[4] = extraPolate(data, _$Ppipe$PflowModel$Pstates$lB1$rB$Pp(1) /*old1*/, _$Ppipe$PflowModel$Pstates$lB1$rB$Pp(2) /*old2*/, $P$ATTRIBUTE$Ppipe$PflowModel$Pstates$lB1$rB$Pp.min, $P$ATTRIBUTE$Ppipe$PflowModel$Pstates$lB1$rB$Pp.max);
  data->simulationInfo.nonlinearSystemData[0].nlsx[5] = $Ptank1$Pmb_flow;
  data->simulationInfo.nonlinearSystemData[0].nlsxOld[5] = _$Ptank1$Pmb_flow(1) /*old1*/;
  data->simulationInfo.nonlinearSystemData[0].nlsxExtrapolation[5] = extraPolate(data, _$Ptank1$Pmb_flow(1) /*old1*/, _$Ptank1$Pmb_flow(2) /*old2*/, $P$ATTRIBUTE$Ptank1$Pmb_flow.min, $P$ATTRIBUTE$Ptank1$Pmb_flow.max);
  retValue = solve_nonlinear_system(data, threadData, 0);
  /* check if solution process was successful */
  if (retValue > 0){
    const int indexes[2] = {1,106};
    throwStreamPrintWithEquationIndexes(threadData, indexes, "Solving non-linear system 106 failed at time=%.15g.\nFor more information please use -lv LOG_NLS.", data->localData[0]->timeValue);
  }
  /* write solution */
  $Ptank2$Ps$lB1$rB = data->simulationInfo.nonlinearSystemData[0].nlsx[0];
  $Ptank1$Ps$lB1$rB = data->simulationInfo.nonlinearSystemData[0].nlsx[1];
  $Ptank2$Pports$lB1$rB$Pp = data->simulationInfo.nonlinearSystemData[0].nlsx[2];
  $Ppipe$PflowModel$Pstates$lB2$rB$Pp = data->simulationInfo.nonlinearSystemData[0].nlsx[3];
  $Ppipe$PflowModel$Pstates$lB1$rB$Pp = data->simulationInfo.nonlinearSystemData[0].nlsx[4];
  $Ptank1$Pmb_flow = data->simulationInfo.nonlinearSystemData[0].nlsx[5];
  TRACE_POP
}
/*
 equation index: 107
 type: SIMPLE_ASSIGN
 der(tank1._m) = tank1.mb_flow
 */
void PipesValveDiscrete_eqFunction_107(DATA *data, threadData_t *threadData)
{
  TRACE_PUSH
  const int equationIndexes[2] = {1,107};
  $P$DER$Ptank1$Pm = $Ptank1$Pmb_flow;
  TRACE_POP
}
/*
 equation index: 108
 type: SIMPLE_ASSIGN
 der(tank2._m) = -tank1.mb_flow
 */
void PipesValveDiscrete_eqFunction_108(DATA *data, threadData_t *threadData)
{
  TRACE_PUSH
  const int equationIndexes[2] = {1,108};
  $P$DER$Ptank2$Pm = (-$Ptank1$Pmb_flow);
  TRACE_POP
}
/*
 equation index: 109
 type: SIMPLE_ASSIGN
 tank1._portVelocities[1] = smooth(0, DIVISION(tank1.mb_flow, Modelica.Fluid.Vessels.OpenTank$tank1.Medium.density(Modelica.Fluid.Vessels.OpenTank$tank1.Medium.setState_phX(tank1.vessel_ps_static[1], smooth(0, if tank1.mb_flow > 0.0 then pipe.port_a.h_outflow else tank1.ports[1].h_outflow), {})) * tank1.portAreas[1]))
 */
void PipesValveDiscrete_eqFunction_109(DATA *data, threadData_t *threadData)
{
  TRACE_PUSH
  const int equationIndexes[2] = {1,109};
  modelica_boolean tmp18;
  tmp18 = Greater($Ptank1$Pmb_flow,0.0);
  $Ptank1$PportVelocities$lB1$rB = DIVISION_SIM($Ptank1$Pmb_flow,(omc_Modelica_Fluid_Vessels_OpenTank$tank1_Medium_density(threadData, omc_Modelica_Fluid_Vessels_OpenTank$tank1_Medium_setState__phX(threadData, $Ptank1$Pvessel_ps_static$lB1$rB, (tmp18?$Ppipe$Pport_a$Ph_outflow:$Ptank1$Pports$lB1$rB$Ph_outflow), _OMC_LIT34)) * $Ptank1$PportAreas$lB1$rB),"Modelica.Fluid.Vessels.OpenTank$tank1.Medium.density(Modelica.Fluid.Vessels.OpenTank$tank1.Medium.setState_phX(tank1.vessel_ps_static[1], smooth(0, if tank1.mb_flow > 0.0 then pipe.port_a.h_outflow else tank1.ports[1].h_outflow), {})) * tank1.portAreas[1]",equationIndexes);
  TRACE_POP
}
/*
 equation index: 110
 type: SIMPLE_ASSIGN
 tank1._ports_E_flow[1] = tank1.mb_flow * (0.5 * tank1.portVelocities[1] ^ 2.0 + system.g * tank1.portsData[1].height)
 */
void PipesValveDiscrete_eqFunction_110(DATA *data, threadData_t *threadData)
{
  TRACE_PUSH
  const int equationIndexes[2] = {1,110};
  modelica_real tmp19;
  tmp19 = $Ptank1$PportVelocities$lB1$rB;
  $Ptank1$Pports_E_flow$lB1$rB = ($Ptank1$Pmb_flow * ((0.5 * (tmp19 * tmp19)) + ($Psystem$Pg * $Ptank1$PportsData$lB1$rB$Pheight)));
  TRACE_POP
}
/*
 equation index: 111
 type: SIMPLE_ASSIGN
 tank1._ports_H_flow[1] = tank1.mb_flow * smooth(0, if tank1.mb_flow > 0.0 then pipe.port_a.h_outflow else tank1.ports[1].h_outflow)
 */
void PipesValveDiscrete_eqFunction_111(DATA *data, threadData_t *threadData)
{
  TRACE_PUSH
  const int equationIndexes[2] = {1,111};
  modelica_boolean tmp20;
  tmp20 = Greater($Ptank1$Pmb_flow,0.0);
  $Ptank1$Pports_H_flow$lB1$rB = ($Ptank1$Pmb_flow * (tmp20?$Ppipe$Pport_a$Ph_outflow:$Ptank1$Pports$lB1$rB$Ph_outflow));
  TRACE_POP
}
/*
 equation index: 112
 type: SIMPLE_ASSIGN
 tank1._Hb_flow = tank1.ports_H_flow[1] + tank1.ports_E_flow[1]
 */
void PipesValveDiscrete_eqFunction_112(DATA *data, threadData_t *threadData)
{
  TRACE_PUSH
  const int equationIndexes[2] = {1,112};
  $Ptank1$PHb_flow = ($Ptank1$Pports_H_flow$lB1$rB + $Ptank1$Pports_E_flow$lB1$rB);
  TRACE_POP
}
/*
 equation index: 113
 type: SIMPLE_ASSIGN
 der(tank1._U) = tank1.Hb_flow
 */
void PipesValveDiscrete_eqFunction_113(DATA *data, threadData_t *threadData)
{
  TRACE_PUSH
  const int equationIndexes[2] = {1,113};
  $P$DER$Ptank1$PU = $Ptank1$PHb_flow;
  TRACE_POP
}
/*
 equation index: 114
 type: SIMPLE_ASSIGN
 der(tank1._medium._u) = DIVISION(tank1.Hb_flow - tank1.mb_flow * tank1.medium.u, tank1.m)
 */
void PipesValveDiscrete_eqFunction_114(DATA *data, threadData_t *threadData)
{
  TRACE_PUSH
  const int equationIndexes[2] = {1,114};
  $P$DER$Ptank1$Pmedium$Pu = DIVISION_SIM(($Ptank1$PHb_flow - ($Ptank1$Pmb_flow * $Ptank1$Pmedium$Pu)),$Ptank1$Pm,"tank1.m",equationIndexes);
  TRACE_POP
}
/*
 equation index: 115
 type: SIMPLE_ASSIGN
 der(tank1._medium._T_degC) = (-$DER.tank1.medium.u) / -4184.0
 */
void PipesValveDiscrete_eqFunction_115(DATA *data, threadData_t *threadData)
{
  TRACE_PUSH
  const int equationIndexes[2] = {1,115};
  modelica_real tmp21;
  tmp21 = -4184.0;
  if (tmp21 == 0) {throwStreamPrint(threadData, "Division by zero %s", "(-$DER.tank1.medium.u) / -4184.0");}
  $P$DER$Ptank1$Pmedium$PT_degC = ((-$P$DER$Ptank1$Pmedium$Pu) / -4184.0);
  TRACE_POP
}
/*
 equation index: 116
 type: SIMPLE_ASSIGN
 der(tank1._medium._T) = $DER.tank1.medium.T_degC
 */
void PipesValveDiscrete_eqFunction_116(DATA *data, threadData_t *threadData)
{
  TRACE_PUSH
  const int equationIndexes[2] = {1,116};
  $P$DER$Ptank1$Pmedium$PT = $P$DER$Ptank1$Pmedium$PT_degC;
  TRACE_POP
}
/*
 equation index: 117
 type: SIMPLE_ASSIGN
 der(tank1._fluidVolume) = (-tank1.mb_flow) / -995.586
 */
void PipesValveDiscrete_eqFunction_117(DATA *data, threadData_t *threadData)
{
  TRACE_PUSH
  const int equationIndexes[2] = {1,117};
  modelica_real tmp22;
  tmp22 = -995.586;
  if (tmp22 == 0) {throwStreamPrint(threadData, "Division by zero %s", "(-tank1.mb_flow) / -995.586");}
  $P$DER$Ptank1$PfluidVolume = ((-$Ptank1$Pmb_flow) / -995.586);
  TRACE_POP
}
/*
 equation index: 118
 type: SIMPLE_ASSIGN
 der(tank1._level) = DIVISION($DER.tank1.fluidVolume, tank1.crossArea)
 */
void PipesValveDiscrete_eqFunction_118(DATA *data, threadData_t *threadData)
{
  TRACE_PUSH
  const int equationIndexes[2] = {1,118};
  $P$DER$Ptank1$Plevel = DIVISION_SIM($P$DER$Ptank1$PfluidVolume,$Ptank1$PcrossArea,"tank1.crossArea",equationIndexes);
  TRACE_POP
}
/*
 equation index: 119
 type: SIMPLE_ASSIGN
 pipe._flowModel._Is[1] = (-tank1.mb_flow) * pipe.length
 */
void PipesValveDiscrete_eqFunction_119(DATA *data, threadData_t *threadData)
{
  TRACE_PUSH
  const int equationIndexes[2] = {1,119};
  $Ppipe$PflowModel$PIs$lB1$rB = ((-$Ptank1$Pmb_flow) * $Ppipe$Plength);
  TRACE_POP
}
/*
 equation index: 120
 type: SIMPLE_ASSIGN
 tank2._portVelocities[1] = smooth(0, DIVISION(-tank1.mb_flow, Modelica.Fluid.Vessels.OpenTank$tank2.Medium.density(Modelica.Fluid.Vessels.OpenTank$tank2.Medium.setState_phX(tank2.vessel_ps_static[1], smooth(0, if (-tank1.mb_flow) > 0.0 then valve.port_b.h_outflow else tank2.ports[1].h_outflow), {})) * tank2.portAreas[1]))
 */
void PipesValveDiscrete_eqFunction_120(DATA *data, threadData_t *threadData)
{
  TRACE_PUSH
  const int equationIndexes[2] = {1,120};
  modelica_boolean tmp23;
  tmp23 = Greater((-$Ptank1$Pmb_flow),0.0);
  $Ptank2$PportVelocities$lB1$rB = DIVISION_SIM((-$Ptank1$Pmb_flow),(omc_Modelica_Fluid_Vessels_OpenTank$tank2_Medium_density(threadData, omc_Modelica_Fluid_Vessels_OpenTank$tank2_Medium_setState__phX(threadData, $Ptank2$Pvessel_ps_static$lB1$rB, (tmp23?$Pvalve$Pport_b$Ph_outflow:$Ptank2$Pports$lB1$rB$Ph_outflow), _OMC_LIT34)) * $Ptank2$PportAreas$lB1$rB),"Modelica.Fluid.Vessels.OpenTank$tank2.Medium.density(Modelica.Fluid.Vessels.OpenTank$tank2.Medium.setState_phX(tank2.vessel_ps_static[1], smooth(0, if (-tank1.mb_flow) > 0.0 then valve.port_b.h_outflow else tank2.ports[1].h_outflow), {})) * tank2.portAreas[1]",equationIndexes);
  TRACE_POP
}
/*
 equation index: 121
 type: SIMPLE_ASSIGN
 tank2._ports_E_flow[1] = (-tank1.mb_flow) * (0.5 * tank2.portVelocities[1] ^ 2.0 + system.g * tank2.portsData[1].height)
 */
void PipesValveDiscrete_eqFunction_121(DATA *data, threadData_t *threadData)
{
  TRACE_PUSH
  const int equationIndexes[2] = {1,121};
  modelica_real tmp24;
  tmp24 = $Ptank2$PportVelocities$lB1$rB;
  $Ptank2$Pports_E_flow$lB1$rB = ((-$Ptank1$Pmb_flow) * ((0.5 * (tmp24 * tmp24)) + ($Psystem$Pg * $Ptank2$PportsData$lB1$rB$Pheight)));
  TRACE_POP
}
/*
 equation index: 122
 type: SIMPLE_ASSIGN
 tank2._ports_H_flow[1] = (-tank1.mb_flow) * smooth(0, if (-tank1.mb_flow) > 0.0 then valve.port_b.h_outflow else tank2.ports[1].h_outflow)
 */
void PipesValveDiscrete_eqFunction_122(DATA *data, threadData_t *threadData)
{
  TRACE_PUSH
  const int equationIndexes[2] = {1,122};
  modelica_boolean tmp25;
  tmp25 = Greater((-$Ptank1$Pmb_flow),0.0);
  $Ptank2$Pports_H_flow$lB1$rB = ((-$Ptank1$Pmb_flow) * (tmp25?$Pvalve$Pport_b$Ph_outflow:$Ptank2$Pports$lB1$rB$Ph_outflow));
  TRACE_POP
}
/*
 equation index: 123
 type: SIMPLE_ASSIGN
 tank2._Hb_flow = tank2.ports_H_flow[1] + tank2.ports_E_flow[1]
 */
void PipesValveDiscrete_eqFunction_123(DATA *data, threadData_t *threadData)
{
  TRACE_PUSH
  const int equationIndexes[2] = {1,123};
  $Ptank2$PHb_flow = ($Ptank2$Pports_H_flow$lB1$rB + $Ptank2$Pports_E_flow$lB1$rB);
  TRACE_POP
}
/*
 equation index: 124
 type: SIMPLE_ASSIGN
 der(tank2._U) = tank2.Hb_flow
 */
void PipesValveDiscrete_eqFunction_124(DATA *data, threadData_t *threadData)
{
  TRACE_PUSH
  const int equationIndexes[2] = {1,124};
  $P$DER$Ptank2$PU = $Ptank2$PHb_flow;
  TRACE_POP
}
/*
 equation index: 125
 type: SIMPLE_ASSIGN
 der(tank2._medium._u) = DIVISION(tank2.Hb_flow + tank1.mb_flow * tank2.medium.u, tank2.m)
 */
void PipesValveDiscrete_eqFunction_125(DATA *data, threadData_t *threadData)
{
  TRACE_PUSH
  const int equationIndexes[2] = {1,125};
  $P$DER$Ptank2$Pmedium$Pu = DIVISION_SIM(($Ptank2$PHb_flow + ($Ptank1$Pmb_flow * $Ptank2$Pmedium$Pu)),$Ptank2$Pm,"tank2.m",equationIndexes);
  TRACE_POP
}
/*
 equation index: 126
 type: SIMPLE_ASSIGN
 der(tank2._medium._T_degC) = (-$DER.tank2.medium.u) / -4184.0
 */
void PipesValveDiscrete_eqFunction_126(DATA *data, threadData_t *threadData)
{
  TRACE_PUSH
  const int equationIndexes[2] = {1,126};
  modelica_real tmp26;
  tmp26 = -4184.0;
  if (tmp26 == 0) {throwStreamPrint(threadData, "Division by zero %s", "(-$DER.tank2.medium.u) / -4184.0");}
  $P$DER$Ptank2$Pmedium$PT_degC = ((-$P$DER$Ptank2$Pmedium$Pu) / -4184.0);
  TRACE_POP
}
/*
 equation index: 127
 type: SIMPLE_ASSIGN
 der(tank2._medium._T) = $DER.tank2.medium.T_degC
 */
void PipesValveDiscrete_eqFunction_127(DATA *data, threadData_t *threadData)
{
  TRACE_PUSH
  const int equationIndexes[2] = {1,127};
  $P$DER$Ptank2$Pmedium$PT = $P$DER$Ptank2$Pmedium$PT_degC;
  TRACE_POP
}
/*
 equation index: 128
 type: SIMPLE_ASSIGN
 der(tank2._fluidVolume) = tank1.mb_flow / -995.586
 */
void PipesValveDiscrete_eqFunction_128(DATA *data, threadData_t *threadData)
{
  TRACE_PUSH
  const int equationIndexes[2] = {1,128};
  modelica_real tmp27;
  tmp27 = -995.586;
  if (tmp27 == 0) {throwStreamPrint(threadData, "Division by zero %s", "tank1.mb_flow / -995.586");}
  $P$DER$Ptank2$PfluidVolume = ($Ptank1$Pmb_flow / -995.586);
  TRACE_POP
}
/*
 equation index: 129
 type: SIMPLE_ASSIGN
 der(tank2._level) = DIVISION($DER.tank2.fluidVolume, tank2.crossArea)
 */
void PipesValveDiscrete_eqFunction_129(DATA *data, threadData_t *threadData)
{
  TRACE_PUSH
  const int equationIndexes[2] = {1,129};
  $P$DER$Ptank2$Plevel = DIVISION_SIM($P$DER$Ptank2$PfluidVolume,$Ptank2$PcrossArea,"tank2.crossArea",equationIndexes);
  TRACE_POP
}
/*
 equation index: 130
 type: SIMPLE_ASSIGN
 valve._port_b_T = Modelica.Fluid.Utilities.regStep(tank1.mb_flow, Modelica.Fluid.Valves.ValveDiscrete$valve.Medium.temperature(Modelica.Fluid.Valves.ValveDiscrete$valve.Medium.ThermodynamicState(tank2.ports[1].p, valve.state_b.T)), Modelica.Fluid.Valves.ValveDiscrete$valve.Medium.temperature(Modelica.Fluid.Valves.ValveDiscrete$valve.Medium.setState_phX(tank2.ports[1].p, valve.port_b.h_outflow, {})), valve.m_flow_small)
 */
void PipesValveDiscrete_eqFunction_130(DATA *data, threadData_t *threadData)
{
  TRACE_PUSH
  const int equationIndexes[2] = {1,130};
  $Pvalve$Pport_b_T = omc_Modelica_Fluid_Utilities_regStep(threadData, $Ptank1$Pmb_flow, omc_Modelica_Fluid_Valves_ValveDiscrete$valve_Medium_temperature(threadData, omc_Modelica_Fluid_Valves_ValveDiscrete$valve_Medium_ThermodynamicState(threadData, $Ptank2$Pports$lB1$rB$Pp, $Pvalve$Pstate_b$PT)), omc_Modelica_Fluid_Valves_ValveDiscrete$valve_Medium_temperature(threadData, omc_Modelica_Fluid_Valves_ValveDiscrete$valve_Medium_setState__phX(threadData, $Ptank2$Pports$lB1$rB$Pp, $Pvalve$Pport_b$Ph_outflow, _OMC_LIT33)), $Pvalve$Pm_flow_small);
  TRACE_POP
}
/*
 equation index: 131
 type: SIMPLE_ASSIGN
 pipe._flowModel._vs[1] = DIVISION(-tank1.mb_flow, pipe.crossArea * Modelica.Fluid.Pipes.StaticPipe$pipe.Medium.density((*.Modelica.Fluid.Pipes.StaticPipe$pipe.Medium.ThermodynamicState*)(pipe.flowModel.states[1])) * pipe.nParallel)
 */
void PipesValveDiscrete_eqFunction_131(DATA *data, threadData_t *threadData)
{
  TRACE_PUSH
  const int equationIndexes[2] = {1,131};
  $Ppipe$PflowModel$Pvs$lB1$rB = DIVISION_SIM((-$Ptank1$Pmb_flow),(($Ppipe$PcrossArea * omc_Modelica_Fluid_Pipes_StaticPipe$pipe_Medium_density(threadData, omc_Modelica_Fluid_Pipes_StaticPipe$pipe_FlowModel$pipe$flowModel_Medium_ThermodynamicState(threadData, $Ppipe$PflowModel$Pstates$lB1$rB$Pp, $Ppipe$PflowModel$Pstates$lB1$rB$PT))) * $Ppipe$PnParallel),"pipe.crossArea * Modelica.Fluid.Pipes.StaticPipe$pipe.Medium.density(/*.Modelica.Fluid.Pipes.StaticPipe$pipe.Medium.ThermodynamicState*/(pipe.flowModel.states[1])) * pipe.nParallel",equationIndexes);
  TRACE_POP
}
/*
 equation index: 132
 type: SIMPLE_ASSIGN
 valve._port_a_T = Modelica.Fluid.Utilities.regStep(-tank1.mb_flow, Modelica.Fluid.Valves.ValveDiscrete$valve.Medium.temperature(Modelica.Fluid.Valves.ValveDiscrete$valve.Medium.ThermodynamicState(pipe.flowModel.states[2].p, valve.state_a.T)), Modelica.Fluid.Valves.ValveDiscrete$valve.Medium.temperature(Modelica.Fluid.Valves.ValveDiscrete$valve.Medium.setState_phX(pipe.flowModel.states[2].p, tank2.ports[1].h_outflow, {})), valve.m_flow_small)
 */
void PipesValveDiscrete_eqFunction_132(DATA *data, threadData_t *threadData)
{
  TRACE_PUSH
  const int equationIndexes[2] = {1,132};
  $Pvalve$Pport_a_T = omc_Modelica_Fluid_Utilities_regStep(threadData, (-$Ptank1$Pmb_flow), omc_Modelica_Fluid_Valves_ValveDiscrete$valve_Medium_temperature(threadData, omc_Modelica_Fluid_Valves_ValveDiscrete$valve_Medium_ThermodynamicState(threadData, $Ppipe$PflowModel$Pstates$lB2$rB$Pp, $Pvalve$Pstate_a$PT)), omc_Modelica_Fluid_Valves_ValveDiscrete$valve_Medium_temperature(threadData, omc_Modelica_Fluid_Valves_ValveDiscrete$valve_Medium_setState__phX(threadData, $Ppipe$PflowModel$Pstates$lB2$rB$Pp, $Ptank2$Pports$lB1$rB$Ph_outflow, _OMC_LIT33)), $Pvalve$Pm_flow_small);
  TRACE_POP
}
/*
 equation index: 133
 type: SIMPLE_ASSIGN
 valve._V_flow = DIVISION(-tank1.mb_flow, Modelica.Fluid.Utilities.regStep(-tank1.mb_flow, Modelica.Fluid.Valves.ValveDiscrete$valve.Medium.density(Modelica.Fluid.Valves.ValveDiscrete$valve.Medium.ThermodynamicState(pipe.flowModel.states[2].p, valve.state_a.T)), Modelica.Fluid.Valves.ValveDiscrete$valve.Medium.density(Modelica.Fluid.Valves.ValveDiscrete$valve.Medium.ThermodynamicState(tank2.ports[1].p, valve.state_b.T)), valve.m_flow_small))
 */
void PipesValveDiscrete_eqFunction_133(DATA *data, threadData_t *threadData)
{
  TRACE_PUSH
  const int equationIndexes[2] = {1,133};
  $Pvalve$PV_flow = DIVISION_SIM((-$Ptank1$Pmb_flow),omc_Modelica_Fluid_Utilities_regStep(threadData, (-$Ptank1$Pmb_flow), omc_Modelica_Fluid_Valves_ValveDiscrete$valve_Medium_density(threadData, omc_Modelica_Fluid_Valves_ValveDiscrete$valve_Medium_ThermodynamicState(threadData, $Ppipe$PflowModel$Pstates$lB2$rB$Pp, $Pvalve$Pstate_a$PT)), omc_Modelica_Fluid_Valves_ValveDiscrete$valve_Medium_density(threadData, omc_Modelica_Fluid_Valves_ValveDiscrete$valve_Medium_ThermodynamicState(threadData, $Ptank2$Pports$lB1$rB$Pp, $Pvalve$Pstate_b$PT)), $Pvalve$Pm_flow_small),"Modelica.Fluid.Utilities.regStep(-tank1.mb_flow, Modelica.Fluid.Valves.ValveDiscrete$valve.Medium.density(Modelica.Fluid.Valves.ValveDiscrete$valve.Medium.ThermodynamicState(pipe.flowModel.states[2].p, valve.state_a.T)), Modelica.Fluid.Valves.ValveDiscrete$valve.Medium.density(Modelica.Fluid.Valves.ValveDiscrete$valve.Medium.ThermodynamicState(tank2.ports[1].p, valve.state_b.T)), valve.m_flow_small)",equationIndexes);
  TRACE_POP
}
/*
 equation index: 134
 type: SIMPLE_ASSIGN
 pipe._flowModel._vs[2] = DIVISION(-tank1.mb_flow, pipe.crossArea * Modelica.Fluid.Pipes.StaticPipe$pipe.Medium.density((*.Modelica.Fluid.Pipes.StaticPipe$pipe.Medium.ThermodynamicState*)(pipe.flowModel.states[2])) * pipe.nParallel)
 */
void PipesValveDiscrete_eqFunction_134(DATA *data, threadData_t *threadData)
{
  TRACE_PUSH
  const int equationIndexes[2] = {1,134};
  $Ppipe$PflowModel$Pvs$lB2$rB = DIVISION_SIM((-$Ptank1$Pmb_flow),(($Ppipe$PcrossArea * omc_Modelica_Fluid_Pipes_StaticPipe$pipe_Medium_density(threadData, omc_Modelica_Fluid_Pipes_StaticPipe$pipe_FlowModel$pipe$flowModel_Medium_ThermodynamicState(threadData, $Ppipe$PflowModel$Pstates$lB2$rB$Pp, $Ppipe$PflowModel$Pstates$lB2$rB$PT))) * $Ppipe$PnParallel),"pipe.crossArea * Modelica.Fluid.Pipes.StaticPipe$pipe.Medium.density(/*.Modelica.Fluid.Pipes.StaticPipe$pipe.Medium.ThermodynamicState*/(pipe.flowModel.states[2])) * pipe.nParallel",equationIndexes);
  TRACE_POP
}
/*
 equation index: 135
 type: SIMPLE_ASSIGN
 pipe._flowModel._mus_act[1] = if noEvent((-tank1.mb_flow) > 0.0) then pipe.flowModel.mus[1] else pipe.flowModel.mus[2]
 */
void PipesValveDiscrete_eqFunction_135(DATA *data, threadData_t *threadData)
{
  TRACE_PUSH
  const int equationIndexes[2] = {1,135};
  modelica_boolean tmp28;
  tmp28 = Greater((-$Ptank1$Pmb_flow),0.0);
  $Ppipe$PflowModel$Pmus_act$lB1$rB = (tmp28?$Ppipe$PflowModel$Pmus$lB1$rB:$Ppipe$PflowModel$Pmus$lB2$rB);
  TRACE_POP
}
/*
 equation index: 136
 type: SIMPLE_ASSIGN
 pipe._flowModel._rhos_act[1] = if noEvent((-tank1.mb_flow) > 0.0) then pipe.flowModel.rhos[1] else pipe.flowModel.rhos[2]
 */
void PipesValveDiscrete_eqFunction_136(DATA *data, threadData_t *threadData)
{
  TRACE_PUSH
  const int equationIndexes[2] = {1,136};
  modelica_boolean tmp29;
  tmp29 = Greater((-$Ptank1$Pmb_flow),0.0);
  $Ppipe$PflowModel$Prhos_act$lB1$rB = (tmp29?$Ppipe$PflowModel$Prhos$lB1$rB:$Ppipe$PflowModel$Prhos$lB2$rB);
  TRACE_POP
}
/*
 equation index: 137
 type: SIMPLE_ASSIGN
 system._m_flow_nominal = 100.0 * system.m_flow_small
 */
void PipesValveDiscrete_eqFunction_137(DATA *data, threadData_t *threadData)
{
  TRACE_PUSH
  const int equationIndexes[2] = {1,137};
  $Psystem$Pm_flow_nominal = (100.0 * $Psystem$Pm_flow_small);
  TRACE_POP
}
/*
 equation index: 138
 type: SIMPLE_ASSIGN
 tank2._portInDensities[1] = 995.586
 */
void PipesValveDiscrete_eqFunction_138(DATA *data, threadData_t *threadData)
{
  TRACE_PUSH
  const int equationIndexes[2] = {1,138};
  $Ptank2$PportInDensities$lB1$rB = 995.586;
  TRACE_POP
}
/*
 equation index: 139
 type: SIMPLE_ASSIGN
 tank1._portInDensities[1] = 995.586
 */
void PipesValveDiscrete_eqFunction_139(DATA *data, threadData_t *threadData)
{
  TRACE_PUSH
  const int equationIndexes[2] = {1,139};
  $Ptank1$PportInDensities$lB1$rB = 995.586;
  TRACE_POP
}


int PipesValveDiscrete_functionInitialEquations(DATA *data, threadData_t *threadData)
{
  TRACE_PUSH
  
  data->simulationInfo.discreteCall = 1;
  PipesValveDiscrete_eqFunction_1(data, threadData);

  PipesValveDiscrete_eqFunction_2(data, threadData);

  PipesValveDiscrete_eqFunction_3(data, threadData);

  PipesValveDiscrete_eqFunction_4(data, threadData);

  PipesValveDiscrete_eqFunction_5(data, threadData);

  PipesValveDiscrete_eqFunction_6(data, threadData);

  PipesValveDiscrete_eqFunction_7(data, threadData);

  PipesValveDiscrete_eqFunction_8(data, threadData);

  PipesValveDiscrete_eqFunction_9(data, threadData);

  PipesValveDiscrete_eqFunction_10(data, threadData);

  PipesValveDiscrete_eqFunction_11(data, threadData);

  PipesValveDiscrete_eqFunction_12(data, threadData);

  PipesValveDiscrete_eqFunction_13(data, threadData);

  PipesValveDiscrete_eqFunction_14(data, threadData);

  PipesValveDiscrete_eqFunction_15(data, threadData);

  PipesValveDiscrete_eqFunction_16(data, threadData);

  PipesValveDiscrete_eqFunction_17(data, threadData);

  PipesValveDiscrete_eqFunction_18(data, threadData);

  PipesValveDiscrete_eqFunction_19(data, threadData);

  PipesValveDiscrete_eqFunction_20(data, threadData);

  PipesValveDiscrete_eqFunction_21(data, threadData);

  PipesValveDiscrete_eqFunction_22(data, threadData);

  PipesValveDiscrete_eqFunction_23(data, threadData);

  PipesValveDiscrete_eqFunction_24(data, threadData);

  PipesValveDiscrete_eqFunction_25(data, threadData);

  PipesValveDiscrete_eqFunction_26(data, threadData);

  PipesValveDiscrete_eqFunction_27(data, threadData);

  PipesValveDiscrete_eqFunction_28(data, threadData);

  PipesValveDiscrete_eqFunction_29(data, threadData);

  PipesValveDiscrete_eqFunction_30(data, threadData);

  PipesValveDiscrete_eqFunction_31(data, threadData);

  PipesValveDiscrete_eqFunction_32(data, threadData);

  PipesValveDiscrete_eqFunction_33(data, threadData);

  PipesValveDiscrete_eqFunction_34(data, threadData);

  PipesValveDiscrete_eqFunction_35(data, threadData);

  PipesValveDiscrete_eqFunction_36(data, threadData);

  PipesValveDiscrete_eqFunction_37(data, threadData);

  PipesValveDiscrete_eqFunction_38(data, threadData);

  PipesValveDiscrete_eqFunction_39(data, threadData);

  PipesValveDiscrete_eqFunction_40(data, threadData);

  PipesValveDiscrete_eqFunction_41(data, threadData);

  PipesValveDiscrete_eqFunction_42(data, threadData);

  PipesValveDiscrete_eqFunction_43(data, threadData);

  PipesValveDiscrete_eqFunction_44(data, threadData);

  PipesValveDiscrete_eqFunction_45(data, threadData);

  PipesValveDiscrete_eqFunction_46(data, threadData);

  PipesValveDiscrete_eqFunction_47(data, threadData);

  PipesValveDiscrete_eqFunction_48(data, threadData);

  PipesValveDiscrete_eqFunction_49(data, threadData);

  PipesValveDiscrete_eqFunction_50(data, threadData);

  PipesValveDiscrete_eqFunction_51(data, threadData);

  PipesValveDiscrete_eqFunction_52(data, threadData);

  PipesValveDiscrete_eqFunction_53(data, threadData);

  PipesValveDiscrete_eqFunction_54(data, threadData);

  PipesValveDiscrete_eqFunction_55(data, threadData);

  PipesValveDiscrete_eqFunction_56(data, threadData);

  PipesValveDiscrete_eqFunction_57(data, threadData);

  PipesValveDiscrete_eqFunction_58(data, threadData);

  PipesValveDiscrete_eqFunction_59(data, threadData);

  PipesValveDiscrete_eqFunction_60(data, threadData);

  PipesValveDiscrete_eqFunction_61(data, threadData);

  PipesValveDiscrete_eqFunction_62(data, threadData);

  PipesValveDiscrete_eqFunction_63(data, threadData);

  PipesValveDiscrete_eqFunction_64(data, threadData);

  PipesValveDiscrete_eqFunction_65(data, threadData);

  PipesValveDiscrete_eqFunction_66(data, threadData);

  PipesValveDiscrete_eqFunction_67(data, threadData);

  PipesValveDiscrete_eqFunction_68(data, threadData);

  PipesValveDiscrete_eqFunction_69(data, threadData);

  PipesValveDiscrete_eqFunction_70(data, threadData);

  PipesValveDiscrete_eqFunction_71(data, threadData);

  PipesValveDiscrete_eqFunction_72(data, threadData);

  PipesValveDiscrete_eqFunction_73(data, threadData);

  PipesValveDiscrete_eqFunction_74(data, threadData);

  PipesValveDiscrete_eqFunction_75(data, threadData);

  PipesValveDiscrete_eqFunction_76(data, threadData);

  PipesValveDiscrete_eqFunction_77(data, threadData);

  PipesValveDiscrete_eqFunction_78(data, threadData);

  PipesValveDiscrete_eqFunction_79(data, threadData);

  PipesValveDiscrete_eqFunction_80(data, threadData);

  PipesValveDiscrete_eqFunction_81(data, threadData);

  PipesValveDiscrete_eqFunction_82(data, threadData);

  PipesValveDiscrete_eqFunction_83(data, threadData);

  PipesValveDiscrete_eqFunction_84(data, threadData);

  PipesValveDiscrete_eqFunction_85(data, threadData);

  PipesValveDiscrete_eqFunction_86(data, threadData);

  PipesValveDiscrete_eqFunction_87(data, threadData);

  PipesValveDiscrete_eqFunction_88(data, threadData);

  PipesValveDiscrete_eqFunction_89(data, threadData);

  PipesValveDiscrete_eqFunction_90(data, threadData);

  PipesValveDiscrete_eqFunction_106(data, threadData);

  PipesValveDiscrete_eqFunction_107(data, threadData);

  PipesValveDiscrete_eqFunction_108(data, threadData);

  PipesValveDiscrete_eqFunction_109(data, threadData);

  PipesValveDiscrete_eqFunction_110(data, threadData);

  PipesValveDiscrete_eqFunction_111(data, threadData);

  PipesValveDiscrete_eqFunction_112(data, threadData);

  PipesValveDiscrete_eqFunction_113(data, threadData);

  PipesValveDiscrete_eqFunction_114(data, threadData);

  PipesValveDiscrete_eqFunction_115(data, threadData);

  PipesValveDiscrete_eqFunction_116(data, threadData);

  PipesValveDiscrete_eqFunction_117(data, threadData);

  PipesValveDiscrete_eqFunction_118(data, threadData);

  PipesValveDiscrete_eqFunction_119(data, threadData);

  PipesValveDiscrete_eqFunction_120(data, threadData);

  PipesValveDiscrete_eqFunction_121(data, threadData);

  PipesValveDiscrete_eqFunction_122(data, threadData);

  PipesValveDiscrete_eqFunction_123(data, threadData);

  PipesValveDiscrete_eqFunction_124(data, threadData);

  PipesValveDiscrete_eqFunction_125(data, threadData);

  PipesValveDiscrete_eqFunction_126(data, threadData);

  PipesValveDiscrete_eqFunction_127(data, threadData);

  PipesValveDiscrete_eqFunction_128(data, threadData);

  PipesValveDiscrete_eqFunction_129(data, threadData);

  PipesValveDiscrete_eqFunction_130(data, threadData);

  PipesValveDiscrete_eqFunction_131(data, threadData);

  PipesValveDiscrete_eqFunction_132(data, threadData);

  PipesValveDiscrete_eqFunction_133(data, threadData);

  PipesValveDiscrete_eqFunction_134(data, threadData);

  PipesValveDiscrete_eqFunction_135(data, threadData);

  PipesValveDiscrete_eqFunction_136(data, threadData);

  PipesValveDiscrete_eqFunction_137(data, threadData);

  PipesValveDiscrete_eqFunction_138(data, threadData);

  PipesValveDiscrete_eqFunction_139(data, threadData);
  data->simulationInfo.discreteCall = 0;
  
  TRACE_POP
  return 0;
}
int PipesValveDiscrete_functionRemovedInitialEquations(DATA *data, threadData_t *threadData)
{
  TRACE_PUSH
  const int *equationIndexes = NULL;
  double res = 0.0;

  
  TRACE_POP
  return 0;
}

/* funtion initialize mixed systems */
void PipesValveDiscrete_initialMixedSystem(int nMixedSystems, MIXED_SYSTEM_DATA* mixedSystemData)
{
  /* initial mixed systems */
  /* parameter mixed systems */
  /* model mixed systems */
  /* jacobians mixed systems */
}

#if defined(__cplusplus)
}
#endif

