/* Algebraic */
/* Simulation code for PipesValveDiscrete generated by the OpenModelica Compiler OpenModelica 1.9.3. */

#include "openmodelica.h"
#include "openmodelica_func.h"
#include "simulation_data.h"
#include "simulation/simulation_info_xml.h"
#include "simulation/simulation_runtime.h"
#include "util/omc_error.h"
#include "simulation/solver/model_help.h"
#include "simulation/solver/delay.h"
#include "simulation/solver/linearSystem.h"
#include "simulation/solver/nonlinearSystem.h"
#include "simulation/solver/mixedSystem.h"

#include <assert.h>
#include <string.h>

#include "PipesValveDiscrete_functions.h"
#include "PipesValveDiscrete_model.h"
#include "PipesValveDiscrete_literals.h"




#if defined(HPCOM) && !defined(_OPENMP)
  #error "HPCOM requires OpenMP or the results are wrong"
#endif
#if defined(_OPENMP)
  #include <omp.h>
#else
  /* dummy omp defines */
  #define omp_get_max_threads() 1
#endif

#ifdef __cplusplus
extern "C" {
#endif


/* forwarded equations */
extern void PipesValveDiscrete_eqFunction_144(DATA* data, threadData_t *threadData);
extern void PipesValveDiscrete_eqFunction_145(DATA* data, threadData_t *threadData);
extern void PipesValveDiscrete_eqFunction_149(DATA* data, threadData_t *threadData);
extern void PipesValveDiscrete_eqFunction_153(DATA* data, threadData_t *threadData);
extern void PipesValveDiscrete_eqFunction_154(DATA* data, threadData_t *threadData);
extern void PipesValveDiscrete_eqFunction_175(DATA* data, threadData_t *threadData);
extern void PipesValveDiscrete_eqFunction_178(DATA* data, threadData_t *threadData);
extern void PipesValveDiscrete_eqFunction_179(DATA* data, threadData_t *threadData);
extern void PipesValveDiscrete_eqFunction_180(DATA* data, threadData_t *threadData);
extern void PipesValveDiscrete_eqFunction_181(DATA* data, threadData_t *threadData);
extern void PipesValveDiscrete_eqFunction_182(DATA* data, threadData_t *threadData);
extern void PipesValveDiscrete_eqFunction_183(DATA* data, threadData_t *threadData);
extern void PipesValveDiscrete_eqFunction_185(DATA* data, threadData_t *threadData);
extern void PipesValveDiscrete_eqFunction_186(DATA* data, threadData_t *threadData);
extern void PipesValveDiscrete_eqFunction_187(DATA* data, threadData_t *threadData);
extern void PipesValveDiscrete_eqFunction_192(DATA* data, threadData_t *threadData);
extern void PipesValveDiscrete_eqFunction_193(DATA* data, threadData_t *threadData);
extern void PipesValveDiscrete_eqFunction_198(DATA* data, threadData_t *threadData);
extern void PipesValveDiscrete_eqFunction_205(DATA* data, threadData_t *threadData);
extern void PipesValveDiscrete_eqFunction_211(DATA* data, threadData_t *threadData);
extern void PipesValveDiscrete_eqFunction_223(DATA* data, threadData_t *threadData);
extern void PipesValveDiscrete_eqFunction_222(DATA* data, threadData_t *threadData);
extern void PipesValveDiscrete_eqFunction_221(DATA* data, threadData_t *threadData);
extern void PipesValveDiscrete_eqFunction_220(DATA* data, threadData_t *threadData);
extern void PipesValveDiscrete_eqFunction_219(DATA* data, threadData_t *threadData);
extern void PipesValveDiscrete_eqFunction_218(DATA* data, threadData_t *threadData);
extern void PipesValveDiscrete_eqFunction_217(DATA* data, threadData_t *threadData);
extern void PipesValveDiscrete_eqFunction_216(DATA* data, threadData_t *threadData);
extern void PipesValveDiscrete_eqFunction_215(DATA* data, threadData_t *threadData);

static void functionAlg_system0(DATA *data, threadData_t *threadData)
{
  PipesValveDiscrete_eqFunction_144(data, threadData);

  PipesValveDiscrete_eqFunction_145(data, threadData);

  PipesValveDiscrete_eqFunction_149(data, threadData);

  PipesValveDiscrete_eqFunction_153(data, threadData);

  PipesValveDiscrete_eqFunction_154(data, threadData);

  PipesValveDiscrete_eqFunction_175(data, threadData);

  PipesValveDiscrete_eqFunction_178(data, threadData);

  PipesValveDiscrete_eqFunction_179(data, threadData);

  PipesValveDiscrete_eqFunction_180(data, threadData);

  PipesValveDiscrete_eqFunction_181(data, threadData);

  PipesValveDiscrete_eqFunction_182(data, threadData);

  PipesValveDiscrete_eqFunction_183(data, threadData);

  PipesValveDiscrete_eqFunction_185(data, threadData);

  PipesValveDiscrete_eqFunction_186(data, threadData);

  PipesValveDiscrete_eqFunction_187(data, threadData);

  PipesValveDiscrete_eqFunction_192(data, threadData);

  PipesValveDiscrete_eqFunction_193(data, threadData);

  PipesValveDiscrete_eqFunction_198(data, threadData);

  PipesValveDiscrete_eqFunction_205(data, threadData);

  PipesValveDiscrete_eqFunction_211(data, threadData);

  PipesValveDiscrete_eqFunction_223(data, threadData);

  PipesValveDiscrete_eqFunction_222(data, threadData);

  PipesValveDiscrete_eqFunction_221(data, threadData);

  PipesValveDiscrete_eqFunction_220(data, threadData);

  PipesValveDiscrete_eqFunction_219(data, threadData);

  PipesValveDiscrete_eqFunction_218(data, threadData);

  PipesValveDiscrete_eqFunction_217(data, threadData);

  PipesValveDiscrete_eqFunction_216(data, threadData);

  PipesValveDiscrete_eqFunction_215(data, threadData);
}
/* for continuous time variables */
int PipesValveDiscrete_functionAlgebraics(DATA *data, threadData_t *threadData)
{
  TRACE_PUSH

  functionAlg_system0(data, threadData);

  PipesValveDiscrete_function_savePreSynchronous(data, threadData);
  
  TRACE_POP
  return 0;
}

#ifdef __cplusplus
}
#endif
