/* Linearization */
/* Simulation code for PipesValveDiscrete generated by the OpenModelica Compiler OpenModelica 1.9.3. */

#include "openmodelica.h"
#include "openmodelica_func.h"
#include "simulation_data.h"
#include "simulation/simulation_info_xml.h"
#include "simulation/simulation_runtime.h"
#include "util/omc_error.h"
#include "simulation/solver/model_help.h"
#include "simulation/solver/delay.h"
#include "simulation/solver/linearSystem.h"
#include "simulation/solver/nonlinearSystem.h"
#include "simulation/solver/mixedSystem.h"

#include <assert.h>
#include <string.h>

#include "PipesValveDiscrete_functions.h"
#include "PipesValveDiscrete_model.h"
#include "PipesValveDiscrete_literals.h"




#if defined(HPCOM) && !defined(_OPENMP)
  #error "HPCOM requires OpenMP or the results are wrong"
#endif
#if defined(_OPENMP)
  #include <omp.h>
#else
  /* dummy omp defines */
  #define omp_get_max_threads() 1
#endif
#if defined(__cplusplus)
extern "C" {
#endif

const char *PipesValveDiscrete_linear_model_frame()
{
  return "model linear_PipesValveDiscrete\n  parameter Integer n = 4; // states \n  parameter Integer k = 0; // top-level inputs \n  parameter Integer l = 0; // top-level outputs \n"
  "  parameter Real x0[4] = {%s};\n"
  "  parameter Real u0[0] = {%s};\n"
  "  parameter Real A[4,4] = [%s];\n"
  "  parameter Real B[4,0] = zeros(4,0);%s\n"
  "  parameter Real C[0,4] = zeros(0,4);%s\n"
  "  parameter Real D[0,0] = zeros(0,0);%s\n"
  "  Real x[4](start=x0);\n"
  "  input Real u[0];\n"
  "  output Real y[0];\n"
  "\n  Real x_Ptank1Plevel = x[1];\n  Real x_Ptank1PmediumPT = x[2];\n  Real x_Ptank2Plevel = x[3];\n  Real x_Ptank2PmediumPT = x[4];\n      \n"
  "equation\n  der(x) = A * x + B * u;\n  y = C * x + D * u;\nend linear_PipesValveDiscrete;\n";
}
#if defined(__cplusplus)
}
#endif

